### ISSUE TITLE
Bug: Permanent fix for Open Metadata Airflow Integration

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1093]
## User Story

Currently, the airflow integration with Open Metadata fails due to database password resets. Implement a permanent fix for this so we don't have to perform manual adjustments when testing

## User Type(s)

Users, Developers

## Definition of done

- [ ] Fix has been identitifed & applied
- [ ] Fix has been tested
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
This will be fixed in https://github.com/ministryofjustice/data-platform/issues/1191
