### ISSUE TITLE
👥 Spike: Identify Identity Needs for Analytical Platform / Analytical Platform Applications

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1094]
SPIKE: 2 dev days

## User Story

We would like to implement a single identity strategy for all our tooling preferably using AzureAD as the source of both authorisation and authentication. However, we recognise that due to wide variety of tools we use, one strategy might not be sufficient. Thus, to complete this story, we need to collate the identity needs for the tools we currently have on the system or are evaluating for inclusion. (Exclude AP Apps)

## User Type(s)

Developer, Ops Engineer

### Proposal

We need a list of our tools and the following information about how it manages authentication and RBAC:
Superset is listed as an example:

Application: Superset
User Management: External IdP (AzureAD via OIDC)
Group Management: Local
Possible external group management? No (Verify)
Required IAM permissions to work: (What permissions does the IRSA role needs to have to enable operation) High/Universal
Access to datasources managed: Locally, via internal group/permission assignment. 

## Definition of done

- [ ] List generated (of all means of auth-ing to all apps / future apps)
- [ ] Information captured in our docs
- [ ] UR test OR added to continual research plan
