### ISSUE TITLE
Define and Implement Metrics for Monitoring of Cloud Platform-migrated AP Apps

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1095]
## User Story

We need some kind of metrics defined for our CP applications to understand how they're performing. Nothing fancy but things like CPU usage vs request, CPU usage vs limits, OOM restarts, runaway memory consumption etc. Using the new routes defined in the previous story, implement the above for gold-scorecard-form and link it to a new channel in slack.

## Definition of done

- [ ] tests implemented
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

https://github.com/ministryofjustice/analytics-platform-helm-charts/commit/416c4389003228c7460a3ea6591b133df61e844f

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by julialawrence** [comment]
Blocked until Emma returns

**Comment by julialawrence** [comment]
@ymao2 please suggest an app for Emma to test.

**Comment by ymao2** [comment]
The following ones which you can give a go @Emterry 
 - gold-scorecard-app
 - safety-diagnostic-tool
 - bentham-app
 - intel-app-homepage

**Comment by julialawrence** [comment]
@Emterry I'm closing this but could you please add the metrics and alerts you've defined or at least link the PR.
