### ISSUE TITLE
👥 Spike: AzureAD Entitlement Management (time based access)

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#1123]
SPIKE: 

## User Story

As a Data Platform user
I want to give access to resources e.g. data for a fixed period of time
So that access to sensitive data does not persist and is automatically revoked

## Value

DP data producers can manage access and for a fix period of time to reduce long live access.

## Questions / Assumptions / Hypothesis

Entitlement Management is defined [here](https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-overview).

### Hypothesis
If we... enable this
Then... users can only access 'resources' for a given period of time

## Definition of Done
- [ ] Investigate time based access to resources
- [ ] Understand if this can be done in Terraform
- [ ] Demonstrate this at Show and Tell / internally.

**Comment by bagg3rs** [comment]
Slack discussion thread [here](https://mojdt.slack.com/archives/C04M8224WCV/p1690803701731349)

**Comment by bagg3rs** [comment]
Friday Slack huddle [here](https://mojdt.slack.com/archives/C04M8224WCV/p1691762639634849)

**Comment by bagg3rs** [comment]
The Auth0 Rule to enable group based access has been tested in Development successfully. 
This will look for a group based on the app name and check membership.

**Comment by bagg3rs** [comment]
relates FR #2136
