### ISSUE TITLE
🤝 DP on Modernisation Platform

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1184]
This epic is to capture all the work deploying Data Platform's Apps and Tools on Modernisation Platform

* EKS
* MWAA

### Issues

- [ ] https://github.com/ministryofjustice/data-platform/issues/1187
- [ ] https://github.com/ministryofjustice/data-platform/issues/1125
- [ ] https://github.com/ministryofjustice/data-platform/issues/1371
- [x] #1592
- [ ] https://github.com/ministryofjustice/data-platform/issues/1697
- [ ] https://github.com/ministryofjustice/data-platform/issues/1189
- [x] https://github.com/ministryofjustice/data-platform/issues/1188
- [ ] https://github.com/ministryofjustice/data-platform/issues/791
- [ ] https://github.com/ministryofjustice/data-platform/issues/480
- [ ] https://github.com/ministryofjustice/data-platform/issues/1191

- [ ] [#1189](undefined)
- [x] #2023

- [x] #2364
- [x] #2387

**Comment by julialawrence** [comment]
Work completed. Further development activity can be tracked via respective epics.
