### ISSUE TITLE
🤝 Test Permission Set for Airflow User access

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1188]
Same as last time but more generic, for reference https://github.com/ministryofjustice/data-platform/issues/791#issuecomment-1634297755

MP have implemented a policy, permission set and assignment for managing Airflow in Modernisation Platform.

This policy now needs to be tested as is the scope of this ticket.

Definition of Done:
- [ ] Test the new permission set enables authentication with the airflow UI
- [ ] Test that new permission set enables running jobs via the UI
- [ ]  Amend the policy if required and get it reviewed by MP
- [ ]  Document the usage of the new SSO role.

**Comment by julialawrence** [comment]
Was blocked because needed MP to implement. It has now been implemented.

**Comment by jacobwoffenden** [comment]
Closed in favour of #791
