### ISSUE TITLE
Fix Static Analysis + Linting issues generated during import of Airflow Resources

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#1253]
During the import of the Airflow resources, a number of issues have been raised by static analysis and linting. This ticket will cover the work required to rectify them.

**Acceptance Criteria**:

- [ ] SuperLinter shows green against any files created during the import of the existing airflow setup
- [ ] Static Analysis also passes
- [ ] Any changes required to meet these are understood, and if disruption is required to implement them, a rollout plan is in place.

**Comment by julialawrence** [comment]
Covered by #886
