### ISSUE TITLE
Import VPC/Network Components of Airflow Prod into Terraform

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1311]
To help decompose the overall ticket into more manageable chunks, this ticket looks to cover the network related architecture for Airflow, and the process of moving it from management by pulumi into `terraform`. The list of expected resources is:

- [ ] The overall VPC
- [ ] Its associated VPNGateway
- [ ] The internetGateway
- [ ] the EIPs for the IGW
- [ ] The EC2 subnets, public and private (6 total across 3 availability zones)
- [ ] 3 NAT gateways one for each public subnet 
- [ ] The routes of each subnet and its routes and associations (1 per availability zone, for public and private)
- [ ] The flowLog
- [ ] The VPC attachments for Cloud Platform and mojap

For a full list, [please consult this document](https://files.slack.com/files-pri/T01066BNN9G-F05NCACRSQM/prod_latest.txt).

For each, the resource should be defined in the Data Platform repo according to its current state (per the AWS console, as this may be disjointed with the state in pulumi code), and imported to the stack so it can be managed via terraform plan/apply.

**Comment by julialawrence** [comment]
Need updating the new values. Consult the list of components.

**Comment by Gary-H9** [comment]
covered [here](https://github.com/orgs/ministryofjustice/projects/27/views/13?pane=issue&itemId=39373516).
