### ISSUE TITLE
🕵️ Investigate the Usage of an Alternative CNI for EKS cluster to be built in MP

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1371]
As a DevOps Engineer, I would like to investigate which alternative container network interface implementation I can use in preference to deault `vpc-cni` which ships with EKS.
`vpc-cni` while simple to use, assigns pod IP addresses out of the general subnet CIDR ranges. Since we're sharing networking with the rest of Modernisation Platform, this is not a viable strategy as there are not enough IP addresses available in those CIDR ranges for our workloads.

Definition of Done:
- [ ] Identify an appropriate replacement for the CNI plugin to use instead of vpc-cni
- [ ] Determine the best way to deploy
- [ ] Capture the decision in our ADR

**Comment by jacobwoffenden** [comment]
VPC CNI has been chosen
