### ISSUE TITLE
💸 Success Metrics

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1565]
### User Story

As a… DP product team
I need to… understand how we will measure the success of the Data Platform, what metrics we will use and how, and why they are important
So that… we can demonstrate that our work has delivered value

### Value / Purpose

We need to demonstrate value to continue justifying the teams work

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

- [ ] We have documented this for our service assessment pack 
- [ ] Identified what we want to measure to demonstrate success
- [ ] Identify the method for measuring this
- [ ] Test with stakeholders
