### ISSUE TITLE
🔐 Security

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1566]
### User Story

As a… product team 
I need/want/expect to… demonstrate our security compliance through security governance and testing
So that… we can onboard users and data with confidence 

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### List of stories
- [x] #1576 

### Definition of Done

- [ ] Document security by design for alpha
- [ ] Document disaster strategy
- [ ] Plan pen test
- [ ] Review CAF
- [ ] Onboard security architect
