### ISSUE TITLE
Familiarise with Open Metadata

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1573]
## User story

As Developer i want to understand about the functionalities of Open Metadata, so i can figure out options to ingest information about the registered from the 'data as product'

###
Useful Links
[https://docs.open-metadata.org/swagger.html](url)

### Tasks
1. Play with the data catalogue
2. Look into the functionalities available 
3. Investigation on ingestion options and plugins 

## Definition of done
- [ ] Share Knowledge with the team
- [ ] Confluence page - https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4535877633/OpenMetaData+-+WIP
- [ ] Define action points

**Comment by seanprivett** [comment]
No longer relevant
