### ISSUE TITLE
🏷 Catalogue Productionisation

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1581]
### User Story

As a data platform I want to standup a productionisation version of the data catalogue 

### Value / Purpose

So that users have am optimised, streamlined experience to conduct their workflows  

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Utilise Amazon EKS to containerise catalog production components and orchestrate them efficiently.

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green
- [ ] All catalog production components are successfully containerised and managed within the Amazon EKS cluster
- [ ] identity integration
- [ ]
