### ISSUE TITLE
:label: Catalogue Configuration

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1582]
### User Story

As a…
I need/want/expect to…
So that…

### Additional Information

User impact: What level of UI abstraction is needed for which user, what functionality do different users need

_No response_

### Definition of Done

- [ ] abstracted ui that interacts with catalog api
- [ ] UR to test user expectations/needs of abstracted ui
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green
-
## List issues in this epic
- [x] ministryofjustice/data-platform#1573
- [x] ministryofjustice/data-platform#1602 
- [x] ministryofjustice/data-platform#1603 
- [x] ministryofjustice/data-platform#1604 
- [x] ministryofjustice/data-platform#1605

- [x] ministryofjustice/data-platform#2032
