### ISSUE TITLE
⚗ Register a Data Product: Alpha

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1583]
### User Story

As a user 
I expect to be able to register a data product's metadata with the data platform
So that the data product is discoverable for data users

User impact: What metadata fields do we want to be inputted at data ingestion, do data uploaders understand the meta data fields we are presenting to them? how can they be managed/changed during data lifecycle/do they need to be, who may wish to search or audit data held via meta data searching and what are their needs. 

### Definition of Done

- [ ] I can register a basic data product with the data platform API
- [ ] I can view this data product on the data catalogue

### Included stories

- [x] ministryofjustice/data-platform#787
- [x] ministryofjustice/data-platform#1656
- [x] ministryofjustice/data-platform#1194 

- [x] ministryofjustice/data-catalogue#105
