### ISSUE TITLE
💨 Internal Airflow

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1591]
### User Story

As a platform engineering team

I want to host an Apache Airflow instance separate to Amazon MWAA

So that non user DAGS can be scheduled, for example Open Metadata's ingestion

### Value / Purpose

Amazon MWAA uses AWS IAM token based authentication, Open Metadata uses basic authentication to communicate

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Rather than use Open Metadata's dependency packages Airflow, we run a instance as a standalone service

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

### Issues

- [x] #1597
- [x] https://github.com/ministryofjustice/data-platform/issues/1190
