### ISSUE TITLE
⚗ Alter a Data Product: Alpha

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#1593]
### User Story

As a data producer 
I expect to be able to alter a data product's metadata with the data platform
So that the data product can be maintained

### Definition of Done

- [ ] I can alter a data product's metadata
- [ ] I can infer schemas for tabular csv data
- [ ] I can add schemas for a data product
- [ ] I can see the versioning changes on my data product
- [ ] I can view these data product alterations on the data catalog

### List of stories
- [x] https://github.com/ministryofjustice/data-platform/issues/1657
- [x] ministryofjustice/data-platform#1194
- [x] ministryofjustice/data-platform#1662

- [x] ministryofjustice/data-platform#1659
- [x] ministryofjustice/data-platform#1657
- [x] ministryofjustice/data-platform#1107

- [x] ministryofjustice/data-platform#2030
- [ ] ministryofjustice/data-catalogue#94
- [x] ministryofjustice/data-platform#2107
