### ISSUE TITLE
⚗ Data product development tasks

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#1595]
### User story

This is an ongoing epic to capture workflow improvements to development processes within the data as a product team

This will include testing, logging,  api technical stuff,  refactoring, deployment 

### Definition of Done 
 [ ] Completed all the technical stories related to  Alpha 
 
- [x] ministryofjustice/data-platform#1310
- [x] ministryofjustice/data-platform#1577
- [x] ministryofjustice/data-platform#1576
- [x] ministryofjustice/data-platform#1478
- [x] ministryofjustice/data-platform#1305
- [x] ministryofjustice/data-platform#686
- [x] ministryofjustice/data-platform#1316
- [x] ministryofjustice/data-platform#1323
- [x] ministryofjustice/data-platform#1479
- [x] ministryofjustice/data-platform#1321
- [x] ministryofjustice/data-platform#1755 
- [x] ministryofjustice/data-platform#533 
- [x] ministryofjustice/data-platform#686 
- [x] ministryofjustice/data-platform#1384 
- [x] ministryofjustice/data-platform#1321 
- [x] ministryofjustice/data-platform#1323 
- [x] ministryofjustice/data-platform#1478 
- [x] ministryofjustice/data-platform#1685 
- [x] ministryofjustice/data-platform#1686 
- [x] ministryofjustice/data-platform#1317 
- [x] ministryofjustice/data-platform#1618
- [x] ministryofjustice/data-platform#1782 
- [x] ministryofjustice/data-platform#1783 
- [x] ministryofjustice/data-platform#1792 
- [x] ministryofjustice/data-platform#1479 
- [x] ministryofjustice/data-platform#1505 

- [x] ministryofjustice/data-platform#1782
- [x] ministryofjustice/data-platform#1783
- [x] ministryofjustice/data-catalogue#103
- [x] ministryofjustice/data-catalogue#101
- [x] ministryofjustice/data-catalogue#99
- [x] ministryofjustice/data-catalogue#98
- [x] ministryofjustice/data-catalogue#97
- [x] ministryofjustice/data-catalogue#110
