### ISSUE TITLE
📝 Data Platform Discussions

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1599]
### User Story

As oneteam™
We need a permanent, shared place for larger discussions
So that we can pool information and reach consensus

### Value / Purpose

- Have one place for the team to track discussion on thorny technical issues
- Keep track of the number of open discussions so we can avoid analysis paralysis
- Make sure we don't lose track of why we made decisions (i.e. we can summarise the outcomes into ADRs and link back to the discussions)

### Hypothesis

If we move discussions into github actions
Then the whole team will be able to keep track of what we've learned and decided

### List of open discussions
See https://github.com/ministryofjustice/data-platform/discussions

- [ ] https://github.com/ministryofjustice/data-platform/discussions/1517
- [x] https://github.com/ministryofjustice/data-platform/discussions/1520
- [ ] https://github.com/ministryofjustice/data-platform/discussions/1613
- [ ] https://github.com/ministryofjustice/data-platform/discussions/1690
- [x] https://github.com/ministryofjustice/data-platform/issues/1684
- [x] ministryofjustice/data-platform#1666
- [x] ministryofjustice/data-platform#1663

- [x] ministryofjustice/data-platform#1684
