### ISSUE TITLE
💨 Airflow: Pulumi -> Terraform

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1625]
### Summary

The goal of this Epic is to migrate the management of Airflow from Pulumi to Terraform in the `data-platform` repository. In short this means creating the IaC which defines the infrastructure previously managed by Pulumi in Terraform.

The Epic will cover both cluster `airflow-prod` and `airflow-dev`. The Epic does not include the `airflow-sandpit` cluster.

Both clusters are build in the `analytical-platform-data-production` AWS account and the code for the clusters should be stored [here](https://github.com/ministryofjustice/data-platform/tree/main/terraform/aws/analytical-platform-data-production/airflow).

Issues should be added to this Epic where appropriate i.e. if migrating a new piece of the infrastructure an Issue should be created per environment and added below. When a piece of infrastructure is completely migrated it should be noted in the Pulumi Resource list GitHub Issues [dev](https://github.com/ministryofjustice/data-platform/issues/1631) + [prod](https://github.com/ministryofjustice/data-platform/issues/1629).

When all infrastructure is migrated any infrastructure/repos related to Pulumi should be retired/archived etc. 

### Development
- [ ] EKS Cluster and Associated Structures: 
https://github.com/ministryofjustice/data-platform/issues/1239
- [x] IAM Roles:
https://github.com/ministryofjustice/data-platform/issues/1250
- [ ] [Storage](https://github.com/ministryofjustice/data-platform/pull/1251)
- [ ] [VPC/Network Components](https://github.com/ministryofjustice/data-platform/pull/1308)

### Production
- [ ] EKS Cluster and Associated Structures:
https://github.com/ministryofjustice/data-platform/issues/1410
- [ ] IAM Roles:
https://github.com/ministryofjustice/data-platform/issues/1626
- [ ] [Storage](https://github.com/ministryofjustice/data-platform/pull/1373)
- [ ] [VPC/Network Components](https://github.com/ministryofjustice/data-platform/pull/1400) 

Finally:
- [ ] Retire Pulumi Infrastructure

### Other information

Pulumi output:

[dev.txt](https://files.slack.com/files-pri/T01066BNN9G-F05NHLM0936/dev.txt) -> [GitHub Issue](https://github.com/ministryofjustice/data-platform/issues/1631)
[prod_latest.txt](https://files.slack.com/files-pri/T01066BNN9G-F05NCACRSQM/prod_latest.txt) -> [GitHub Issue](https://github.com/ministryofjustice/data-platform/issues/1629).

**Comment by Gary-H9** [comment]
I've gone through the Terraform state / current `data-platform` repository content / pulumi txt files. I now believe that the GitHub issues are up to date for both [dev](https://github.com/ministryofjustice/data-platform/issues/1631) and [prod](https://github.com/ministryofjustice/data-platform/issues/1629). 

Anything which is migrated from Pulumi to Terraform should be noted in these Issues.

Before this Epic is declared finished anything remaining 'unticked' in the issues should be resolved or declared out of scope.
