### ISSUE TITLE
⚙ Automate generating and sending JML extracts monthly

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1719]
### User Story

JML project sits across the entire MOJ to identify users that need to be removed. Analytical Platform takes part in the project by sending an extract of our Auth0 logs to the project can identity AP users who need to be offboarded.

Generation of this extract needs to be automated. 

### Value / Purpose

The format of the extract is consistent  from month to month and doesn't change. With the data now going to CloudWatch and query to extract information defined, this is a perfect candidate for automation. 

This is a high-visibility project so making sure we deliver the extract in a timely manner.

### Useful Contacts

@julialawrence 

### User Types

DP Ops

### Hypothesis

If we automate this, this will remove the mental load of having to remember to do this monthly.

### Proposal

Use CloudWatch Insight query and a lambda or a step function to generate the extract and mail it.

### Additional Information

Prerequisite: #1742 

### Definition of Done

- [ ] Implement the extract 
- [ ]  Confirm sending successfully

**Comment by jhpyke** [comment]
Pushing to next sprint due to lack of logs in account and other team priorties. Current implementation is mostly done - needs addition of secret with API key, as well as build and upload of image to ECR for testing. [All work is in this branch](https://github.com/ministryofjustice/data-platform/tree/JML-scripting-branch).

**Comment by jhpyke** [comment]
Current progress - 

**Completed**

- [x] Basic Lambda Code provisioned
- [x] [An ECR repository has been made in MP to store the image](https://github.com/ministryofjustice/modernisation-platform/pull/5412/files)
- [x] Lambda code tested locally

**TODO:**

- [x] Create Lambda role with correct permissions to access cloudwatch logs and AWS SecretsManger
- [x] Change hard-coded values in function calls into variables within code
- [x] Add Secret Values (currently in 1Password) for Gov.UK Notify into AWS SecretsManager [in Modernisation Platform](https://github.com/ministryofjustice/modernisation-platform/blob/509056834c2ed107e56c00532abefdc842343980/terraform/environments/data-platform-apps-and-tools/secrets.tf) This will need you to provision the secret, and then manually enter the value via the AWS console once it has been created. We will need a secret for the API key, and another for the email (correct email can be got from our PM). UNDER NO CIRCUMSTANCES SHOULD THE EMAIL BE COMMITTED TO CODE DIRECTLY, AS THIS IS A PUBLIC REPO
- [x] Replace placeholder values with correct underlying ones (In case of email, this should be replaced with a secret.
- [x] Build and Upload image to created ECR repo
- [ ] Test Lambda against logs in S3

**Comment by murad-ali-MoJ** [comment]
Create two roles for a Lambda function—one to grant access to CloudWatch and another to grant access to Secrets Manager. https://github.com/ministryofjustice/modernisation-platform/pull/5937/files @jhpyke

**Comment by murad-ali-MoJ** [comment]
Added terraform code to the modernisation-platform for Gov.UK notification. The code needs to be modified with the API key from 1PASSWORD. https://github.com/ministryofjustice/modernisation-platform/pull/5942 @jhpyke

**Comment by Ed-Bajo** [comment]
@jhpyke  Please see below for the note from the JML team regarding thweier monthly extraction:
The extract was provided in .xls (Excel 97-2003 Workbook) format. The correct format is .xlsx (Excel Workbook).
The ‘Effective Date’ field should be ‘Effective Date of Data’.
The ‘Employee Email’ field should be ‘Employee Email Address’
The ‘Last Login Date’ field should be ‘Last login date’ – noting the case sensitivity.
The tab name provided was ‘logs-insights-results (1)’. It should be ‘Data’.

**Comment by murad-ali-MoJ** [comment]
@Ed-Bajo the code has been updated based on your requirements and the newly generated Excel file has been sent to your Slack.

**Comment by murad-ali-MoJ** [comment]
created [PR](https://github.com/ministryofjustice/modernisation-platform/pull/5937) for roles and secrets and requested the ask-modernisation-platform to review.

**Comment by murad-ali-MoJ** [comment]
The final [PR](https://github.com/ministryofjustice/modernisation-platform-environments/pull/4636) has been approved by the modernisation platform. Now, we will merge the PR and test against the logs.

**Comment by murad-ali-MoJ** [comment]
Testing failed due to a mismatch between the handler and the lambda function. I rectified the problem and raised a pull request (PR) for modernisation-platform However, the PR failed due to some unrelated resources being added. I raised the issue in the modernisation-platform channel, and they are currently investigating the problem.

**Comment by jacobwoffenden** [comment]
Closing as shipped 🎉
