### ISSUE TITLE
Break down Identity Epic

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1727]
### User Story

As members of the Data Platform Apps and Tools, we want to break down the identity epic so we can understand our journey and the deliverables for our identity strategy in Alpha and beyond.

### Hypothesis

If we agree a common identity strategy we can make plans how to implement it.

### Proposal

Hold a whiteboarding session with the whole team to break down our identity strategy and our approach to implementation.
In scope for the meeting:
* Assessing our current state of identity in AP and DP
* Agreed the common interface for identity management
* Discuss proposals of implementation of common identity strategy across the platform
* TBD

### Definition of Done

- [x] Document our current state of identity and access management, capturing all identity and middlewear providers and what uses what.
- [x] Document our Data Platform Identity Strategy and make it available in our documentation
- [x] Agree proof of concepts to test aspects of identity strategy
- [x] Validate strategy with other Data Platform stakeholders
- [x] Raise follow-on stories

**Comment by julialawrence** [comment]
https://docs.google.com/document/d/1VKnbJpNfw4UZDUQ3RCjdWeJASBjSjpfpDRDY044JmYM/edit#heading=h.6bdcpvwr740s
