### ISSUE TITLE
Implement Auth0 Log Collection in Modernisation Platform

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1742]
### User Story

We need to move Auth0 logs to MP.

### Value / Purpose

Currently we are collecting auth0 logs in a cloudwatch log group in Analytical Platform account and we'd like to collect this in the observability account or one of our own MP accounts so we can ingest them into our logging stack. 

### Useful Contacts
N/A

### User Types

This is chiefly for Data Platform operators and security

### Hypothesis

Moving this into MP brings us closer to the goal of retiring our AP accounts.

### Proposal

Recreate Auth0 native log stream and point to Observability Platform, this is in code ([link](https://github.com/ministryofjustice/data-platform/blob/main/terraform/aws/analytical-platform-development/open-metadata/auth0-log-streams.tf))

- [x] Phase one: Create Auth0 log streams in data-platform
- [x] Phase two: Create AWS resources in modernisation-platform-environments
- [x] Phase three: Migrate firebreak created resources to new components
- [x] Phase four: Fix analytical-platform-development streaming (sorry @julialawrence)

### Definition of Done

- [x] Auth0 logs are being streamed into MP ~rather than AP account~

**Comment by jacobwoffenden** [comment]
17/10/23 refinement: for @julialawrence to provide details

**Comment by Emterry** [comment]
closed by accident

**Comment by Gary-H9** [comment]
Phase 1/3 was done [here](https://github.com/ministryofjustice/data-platform/pull/2274). 
Phase 2 was done [here](https://github.com/ministryofjustice/modernisation-platform-environments/pull/3973).

**Comment by jacobwoffenden** [comment]
Phase 4 ➡️ https://github.com/ministryofjustice/data-platform/pull/2326
