### ISSUE TITLE
🖥️ Discuss Register a Data Product workflow with Labs and UR

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1743]
### User story
As a user who wants to publish a data product to other data users
I want to have a UI for me to create the data product and upload the data 
afterwards I can query the data through AWS athena

Key steps 
- Login the Control panel
- View a list of data products
  - Search the existing data products (**optional step and outside this ticket scope**)
- Start the follow UI-wizard style to
  - Mandatory step: Data product by providing the metadata required
  - Optional step : Provide the dataset's schema required
  - Optional step: Upload the data 
  - Each step should provide the information to allow user to know what was happening and any error 
- At end of the above steps, outcome should include 
  - The metadata of the data product should be pushed into OMD
  - The user that registered the data-product (data product owner) should be granted permission to access this data product including: 
    - Querying the data from Athena
    - View the metadata from OMD

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Meet with Labs and UR teams to discuss the three workflows and reconcile them:

Data Labs user flow diagrams:
https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4557963328/user+journeys+via+API+WIP

DPAT Flow diagram
Maps interaction between the UI and Data Labs API, following further meetings and discussions with the Labs team regarding their user flows (above)
https://mojdt.slack.com/archives/C04M8224WCV/p1699530766006839?thread_ts=1699530636.781139&cid=C04M8224WCV

UR Diagram of workflow -includes mock up screenshots
https://mojdt.slack.com/archives/C04M8224WCV/p1700475440273509?thread_ts=1700474205.715399&cid=C04M8224WCV

### Additional Information

Older diagrams for reference:

UI design idea based on discussions at London meeting on 25/10/23
https://mojdt.slack.com/archives/C04M8224WCV/p1699530650541059?thread_ts=1699530636.781139&cid=C04M8224WCV

Interactive flow diagram based on discussions at London meeting on 25/10/23
https://mojdt.slack.com/archives/C04M8224WCV/p1699530667900729?thread_ts=1699530636.781139&cid=C04M8224WCV

### Definition of Done

- [ ] Meeting with Labs and UR team to go through the multiple workflow diagrams/mock ups
- [ ] Document the outcome
- [ ] Agree on way of working between teams going forward

**Comment by jacobwoffenden** [comment]
17/10/23 refinement: further refine after control panel exploration session (25/10/23)

**Comment by ymao2** [comment]
update on 30/10/2023:   we will have a meeting on Friday,  after meeting, the ticket should be updated with outcome

**Comment by ymao2** [comment]
Flow diagram to map interaction between the UI and Data Labs API
https://mojdt.slack.com/archives/C04M8224WCV/p1699530766006839?thread_ts=1699530636.781139&cid=C04M8224WCV

**Comment by ymao2** [comment]
last update: will hold another meeting this week to clarify the following detail 
- Auth between control panel and data labs APIs
- The detail about data uploading

**Comment by michaeljcollinsuk** [comment]
Update 20/11/23 after discussion with @ymao2 and @mitchdawson1982:

There are multiple user workflows being discussed and drafted by multiple teams (DPAT, Labs, UR - links below in the "Additional Information" section), including some mock up screenshots for usability testing. Before we can implement anything in the new control panel, we need to reconcile these against each other, and agree on a workflow that meets all requirements for all teams. Therefore the scope of this ticket should be to bring all the teams together and discuss the workflow. Some initial discussion points:
- Check mock up screenshots - do they cover everything required for registering a data product with the labs API?
- Clarify splitting the steps across multiple pages - will new control panel need to implement this?
- Go through outstanding questions from DPAT about the Labs API that need to be answered. There questions captured in the DPAT workflow diagram

**Comment by michaeljcollinsuk** [comment]
- Meeting was held on 30/11/23 with members of DPAT, Labs project manager, UR and the service owner
- Discussed the work that had already been undertaken by DPAT for the new Control Panel that would integrate with the data product registration API to provide a UI
- The question of ownership of the UI for the data product registration process was raised - specifically whether this should be the responsibility of the Labs team rather than DPAT
- The outcome was undecided by the end of the meeting, with final decision pending
