### ISSUE TITLE
Use case and testing

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1752]
null
- [x] ministryofjustice/data-platform#1658
- [x] ministryofjustice/data-platform#1751

- [x] ministryofjustice/data-platform#2033
