### ISSUE TITLE
[🔢 ] Deploy shiny app ap-rshiny-notebook into CP as the example project for testing purpose

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1772]
### User Story

# Background

As a member of DPAT team
We expect to be able to the following testings before we release new version of shared components used by the shiny apps
- Auth-proxy 
- Shiny-server

# Task 
Deploy the [ap-rshiny-notebook](https://github.com/ministryofjustice/ap-rshiny-notebook) to cp by using the same approach we used for other shiny apps

### Value / Purpose

- Have a app for demoing the major features provided by the DPAT team 
- Have a app for testing the new version of shared components to make sure new changes won't break the apps 
- Have the full freedom for changing the code without worrying for breaking and no dependencies for other apps during internal testing stage.

This app is designed and is developed for this purpose

### Definition of Done

- [X] Copy the repo from `moj-analytical-services` to `ministryofjustice`
- [X] Create the namespace (dev)
- [X] Register the app on cpanel
- [X] aws role for trust-relationshp
- [ ] workflow and deploy to dev
