### ISSUE TITLE
⚗ Spike: Proposal for a simplified UI for permissions management

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1817]
### User Story

We would like a very light weight prototype for an access management UI so we can use it for the purposes of user research.

### Value / Purpose

Although UR doesn't require a proposal upfront, since many AP users and potential DP users have flagged permissions management as a challenging part of onboarding data to the Analytical Platform, we want to make sure we're designing an interface with maximum usability. Putting a proposal in front of users will assist with that goal and better simulate discussion. 

### User Types

Platform operators, data management personas

### Hypothesis

If we put a UI proposal in front of users rather than asking generalised questions, we will get more targeted and actionable feedback. 

### Definition of Done

- [ ] UI proposal completed
- [ ] UI proposal reviewed by the team and stakeholders
- [ ] Further stories raised to carry out user research
- [ ] UI and choices made documented in Data Platform docs
