### ISSUE TITLE
:alembic: Spike: Implement scripts to read and write user AAD group membership information

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1823]
### User Story

We need to agree and implement a proof of concept for synchronising permission information for a user between AzureAD and the application used for the proof of concept.

The following stories need to be completed prior to the commencement of this work:
https://github.com/ministryofjustice/data-platform/issues/1814

Additionally, we need to agree that we will be using groups and define how we map groups against datasources (same name? similar key? Naming convention? etc)

Carried out in tandem with: https://github.com/ministryofjustice/data-platform/issues/943

### Value / Purpose

We need to understand what is required to manage permissions via one interface without forcing users to interact with AzureAD

### User Types

data platform operators and user personas

### Hypothesis

If we're able to implement scripts to sync information between an application and AAD, we will have validated single source of identity approach and single UI for management appraoch.

### Additional Information

We will use the development AzureAD tenant to carry out this work. 

### Definition of Done

- [ ] Define a simple UI or cli to authenticate user against AzureAD which can do the following
- [ ] Ability to define a dummy data source (doesn't need to correspond to actual AWS entity
- [ ] Uses graphAPI to create a group in the development AAD that corresponds to the new datasource
- [ ] Use the CLI/UI to grant a user permission to to the data source
- [ ] Uses GraphAPI to add user to the new group
- [ ] On next authentication, retrieve user's permissions based on group access and update the UI to reflect.

**Comment by julialawrence** [comment]
Completed as part of #943
