### ISSUE TITLE
🚀  Add Managed Prometheus and Managed Grafana

### ISSUE THREAD

**Issue by Emterry** [ministryofjustice/analytical-platform#1825]
### User Story

As a developer 
I want to add managed prometheus and grafana in observability platform on MP, to enable alerting and monitoring of our infrastructure

### Definition of Done

- [x] Add managed prometheus
- [x] Add managed grafana
- [ ] Export metrics to test
- [ ] Set up alerting
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by julialawrence** [comment]
EKS metrics are being remote-written to prom. No alerts. Open up another story to capture alerting @Emterry @jacobwoffenden
