### ISSUE TITLE
🧑‍💻 Apps & Tools BAU

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1827]
### Brief summary of what this Epic is

This is a catch-all epic covering works we carry out as part of our business as usual, such as bug fixes, support requests, process improvements, etc.

- [x] ministryofjustice/analytical-platform#1826
- [x] ministryofjustice/analytical-platform#1746
- [x] ministryofjustice/analytical-platform#1750
- [x] ministryofjustice/analytical-platform#1836
- [x] ministryofjustice/analytical-platform#1869
- [x] ministryofjustice/analytical-platform#1884
- [x] ministryofjustice/analytical-platform#1885
- [x] ministryofjustice/analytical-platform#1719
- [x] ministryofjustice/analytical-platform#1894
- [x] ministryofjustice/analytical-platform#632
- [x] ministryofjustice/analytical-platform#1933
- [x] ministryofjustice/analytical-platform#1948
- [x] ministryofjustice/analytical-platform#1965
- [x] ministryofjustice/analytical-platform#1978
- [x] ministryofjustice/analytical-platform#1980
- [x] ministryofjustice/analytical-platform#1982

- [x] ministryofjustice/analytical-platform#2012
- [x] ministryofjustice/analytical-platform#2035
- [x] ministryofjustice/analytical-platform#1939
- [x] ministryofjustice/analytical-platform#1309
- [x] ministryofjustice/analytical-platform#2137

- [x] ministryofjustice/analytical-platform#2175
- [x] ministryofjustice/analytical-platform#2206
- [x] ministryofjustice/analytical-platform#2149

- [x] ministryofjustice/analytical-platform#2242
- [x] ministryofjustice/analytical-platform#886

- [x] ministryofjustice/analytical-platform#2251
- [x] ministryofjustice/analytical-platform#2268
- [x] ministryofjustice/analytical-platform#2270
- [x] ministryofjustice/analytical-platform#2348
- [x] ministryofjustice/analytical-platform#2389
- [x] ministryofjustice/analytical-platform#2389
- [x] ministryofjustice/analytical-platform#2451
- [x] ministryofjustice/analytical-platform#2452
- [x] ministryofjustice/analytical-platform#2457
- [x] ministryofjustice/analytical-platform#2502
- [x] ministryofjustice/analytical-platform#2551
- [x] ministryofjustice/analytical-platform#2551
- [x] ministryofjustice/analytical-platform#799
- [x] ministryofjustice/analytical-platform#793
- [x] ministryofjustice/analytical-platform#1474
- [x] ministryofjustice/analytical-platform#2763
- [x] ministryofjustice/analytical-platform#2805
- [x] ministryofjustice/analytical-platform#2905
- [x] ministryofjustice/analytical-platform#2907
- [x] ministryofjustice/analytical-platform#2908
- [x] ministryofjustice/analytical-platform#2934
- [x] ministryofjustice/analytical-platform#2959
- [x] ministryofjustice/analytical-platform#2976
- [x] ministryofjustice/analytical-platform#3002
- [x] ministryofjustice/analytical-platform#3007
- [x] ministryofjustice/analytical-platform#3008
- [x] ministryofjustice/analytical-platform#3009
- [x] ministryofjustice/analytical-platform#3044
- [x] ministryofjustice/analytical-platform#2857
- [x] ministryofjustice/analytical-platform#2856
- [x] ministryofjustice/analytical-platform#1829
- [x] ministryofjustice/analytical-platform#3150
- [x] ministryofjustice/analytical-platform#3226
- [x] ministryofjustice/analytical-platform#3237
- [x] ministryofjustice/analytical-platform#3279
- [x] #3395
- [x] ministryofjustice/analytical-platform#3397
- [x] ministryofjustice/analytical-platform#2164
- [x] ministryofjustice/analytical-platform#3272
- [x] ministryofjustice/analytical-platform#3295
- [x] ministryofjustice/analytical-platform#3309

- [x] ministryofjustice/analytical-platform#3398
- [x] ministryofjustice/analytical-platform#3479
- [x] ministryofjustice/analytical-platform#1949
- [x] ministryofjustice/analytical-platform#3700
- [x] ministryofjustice/analytical-platform#3765
- [x] ministryofjustice/analytical-platform#4004
- [x] ministryofjustice/analytical-platform#3236
- [x] ministryofjustice/analytical-platform#4874
- [x] ministryofjustice/analytical-platform#4933
- [ ] ministryofjustice/analytical-platform-ithc-2024#20
