### ISSUE TITLE
🤖 Control panel: Migrate for using task to handling installation of tooling helm chart

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1829]
### Background 

We started the movement to migrate the control panel to use queue/task to handle all those background tasks,  we have done the parts for registering an app and managing the se bucket. 

### Task 

This ticket is to migrate the Control panel to use  sns queue to handle the task of installing the tooling helm charts.

### Value / Purpose

- Make the task easier to be tracked on AWS
- Make the task handling more robust. 
- Prepare the future to split the Control panel to light-weight app for UIs and several backend components for handling different tasks

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

- Create a new queue and use celery task 
- Remove the django-channel for this part

### Definition of Done

- [ ] Documentation has been written / updated
- [ ] The helm chart can be installed via sns queue and celery task
- [ ] Tests are green

**Comment by Gary-H9** [comment]
Please add some details on the implementation @ymao2

**Comment by jacobwoffenden** [comment]
17/10/23 refinement: moving to backlog, this is a piece of work that is not essential functionality, but will align Helm with the other components.

**Comment by julialawrence** [comment]
Edwin to provide clarity.

**Comment by julialawrence** [comment]
Closed as we're focussing on AP UI work.
