### ISSUE TITLE
♻️  Refactor GitHub issues workflows

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1869]
### User Story

As a member of the platform engineering team
I expect all the GitHub Actions workflows to follow the same construct (valid YAML, steps have IDs, steps use commit SHAs)
So that there is uniformity between workflows and Dependabot can properly update the version

### Value / Purpose

To create consistency between all workflows

### User Types

Platform engineering

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Refactor the new GitHub Actions workflows that are used for adding/removing issues to GitHub Projects

### Additional Information

- https://github.com/ministryofjustice/data-platform/blob/main/.github/workflows/github-issues-add-issue-to-epic.yml
- https://github.com/ministryofjustice/data-platform/blob/main/.github/workflows/github-issues-create-epic-label.yml
- https://github.com/ministryofjustice/data-platform/blob/main/.github/workflows/github-issues-remove-issue-from-epic.yml

### Definition of Done

- [ ] Define spec in tech docs
- [ ] Valid YAML, with `---`
- [ ] Steps have an `id`
- [ ] Steps that call marketplace actions use SHA for versioning
- [ ] Permissions are scoped to `job.*` and not workflow level
