### ISSUE TITLE
:alembic: Spike: Investigate updating user permissions in the UI

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1879]
### User Story

We need to investigate and agree an approach to manage user permissions via a graphical user interface, including a two-way sync to our identity provider of choice (AzureAD)

### Value / Purpose

Designing and implementing a two-way sync with AAD is the necessary  first step in delivering a single pane of glass for all Data Platform tooling access.

### User Types

DP Devs, DP Ops, DP Customers

### Hypothesis

If we're able to design and prove the remote sync, we can use this capability to restrict access to data platform as a whole, without opening it up to the entirety of the MOJ. 

Additionally, eventual implementation will allow us to determine the reasonable set of permissions required for the token to access and run GraphAPI requests.

### Proposal

This is a prerequisite to https://github.com/ministryofjustice/data-platform/issues/943

One of the outcomes of the story that need to be captured is whether this approach can be managed in code and if so how.

### Definition of Done

- [ ] Proposal agreed for the approach for authz, circulated to stakeholders and outcome captured in DP docs
- [ ]  Agree appropriate UI for testing
- [ ] Outcomes captured in docs
- [ ] Folllow-on story raised
- [ ] Present at DP Peer Review

**Comment by julialawrence** [comment]
Conversation scheduled with Alex vF to go through this. Might be possible to close once complete.
