### ISSUE TITLE
♻️ Refactor GitHub Terraform component

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1884]
### User Story

As a member of the data platform team
I expect the code which configures our GitHub Teams and Repositories to be easy to read and maintain
So that new members can easily update or add to our configuration

### Value / Purpose

Having easy and simple Terraform should allow our non platform team members to do things like add users to teams

### User Types

Data Platform Team

### Hypothesis

If we refactor the component to make it simpler
Then there should be less friction when interacting with this essential component

### Proposal

_TBC_, but mostly refactoring to make simpler

### Definition of Done

- [ ] Terraform plans and applies
- [ ] No breaking changes are introduced to current resources

### TODO
Reference: https://github.com/orgs/ministryofjustice/teams?query=data-platform
- [x] Retire @ministryofjustice/data-platform-hackathon
  - No longer required
- [ ] Retire @ministryofjustice/data-platform-security-and-auditors
  - Replaced by data-platform-audit-and-security
  - Moved to https://github.com/ministryofjustice/data-platform/issues/2242
- [ ] Retire @ministryofjustice/data-platform-core-infra
  - Replaced by  data-platform-apps-and-tools
  - Moved to https://github.com/ministryofjustice/data-platform/issues/2242
- [x] Retire @ministryofjustice/data-platform-docs-admin-team
  - This was created by Ops Engineering automation, but the repo no longer exists
- [x] Replace @ministryofjustice/data-platform-app-template-admin-team
  - This was created by Ops Engineering automation
- [x] Create data-platform
- [x] Create data-platform-user-centered-design
- [x] Import data-platform-apps-and-tools
- [x] Import data-platform-labs
- [x] Create data-platform-audit-and-security
- [x] Import data-platform-apps-and-tools-airflow-users
- [x] Import data-platform-cloud-platform-development
- [x] Import data-platform-cloud-platform-production
- [x] Delete data-platform-identity
- [x] Archive https://github.com/ministryofjustice/analytics-platform-infrastructure
