### ISSUE TITLE
Spike: Integrate Labs' Logging and metrics into our Monitoring Stack

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1888]
### User Story

Labs are collecting logging and metrics information and we need to understand how it fits into our new Monitoring and Observability stack.

This ticket will cover understanding of how this will be done with implementation carried out in the following sprint. 

### Value / Purpose

This moves us further towards a single pane for alerting and monitoring 

### Proposal

POC: Setting up an IAM role to ingest cloudwatch logs and metrics into our prom and grafana and give labs access to query it. 

### Definition of Done

- [ ] Approach agreed with labs
- [ ] Approach designed
- [ ] Determination about fitness of data for our O&M stack
- [ ] Follow-on stories  raised

**Comment by julialawrence** [comment]
Labs aren't ready to proceed this sprint. Will engage next sprint.

**Comment by Emterry** [comment]
this is a duplicated ticket of #2145
