### ISSUE TITLE
🔱 Investigate using `kube-prometheus-stack` instead of vanilla Prometheus

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1895]
### User Story

As a platform engineer
I want the easiest onramp for monitoring applications in our environment
So that each application doesn't require its own curated monitoring configuration

### Value / Purpose

Using `kube-prometheus-stack` we can utilise the `ServiceMonitor` custom resource definition that comes as part of the Prometheus Operator, this will allow us to make use of 3rd party Helm charts that come with a `serviceMonitor`

### User Types

platform engineering

### Hypothesis

If we switch out to using `kube-prometheus-stack`
Then we utilise the `ServiceMonitor` custom resource definition

### Proposal

Replace the current `prometheus-proxy` Helm chart with `kube-prometheus-stack`, Disabling the built-in AlertManager and Grafana.

### Additional Information

Remote write functionality is still available, it's just configured differently

Reference material: https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/configure-infrastructure-manually/prometheus/remote-write-helm-operator/

### Definition of Done

- [ ] `prometheus-proxy` removed
- [ ] `kube-prometheus-stack` deployed
- [ ] Metrics still delivered to Observability Platform with external_labels (as per current)
- [ ] Enable `serviceMonitor` in Open Metadata and Airflow charts

**Comment by Ed-Bajo** [comment]
The story is quite old and will reopen if needed.
