### ISSUE TITLE
⚗️ Spike: PowerBI for Analytical Platform

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1916]
### User Story

A number of customers of analytical platform have raised a requirement to use PowerBI as a visualising and MI tool. The requirements are urgent as the alternative for these customers is to go out and build their own analytical tools, which is something we want to avoid.

Therefore, we would like to investigate a tactical solution for providing PowerBI to AP customers, with the understanding that all or none of this solution will be carried over to Data Platform.

### Value / Purpose

This will discourage analytical platform customers who have a PowerBI requirement from building their own analytical platform. Splintering right as data platform is being built takes the org away from its mission of having one stop shop for data.

### User Types

AP Customers

### Hypothesis

If we're able to provide a solution, we'll be able to retain more future customers for DP.

### Proposal

None at present. This is a spike

### Definition of Done

- [x] Approach to providing PowerBI agreed
- [x] And documented
- [x] Implementation stories raised
- [x] UR needs captured

**Comment by Gary-H9** [comment]
A lot of the discussion around this piece is captured in the #data-platform-powerbi channel. 

At the moment we have [created](https://github.com/ministryofjustice/data-platform/tree/windows-dev) a Windows EC2 instance for testing.

**Comment by Gary-H9** [comment]
- `t2.micro` -> `t2.small`
- Amazon Athena ODBC Driver installed
- PowerBI Desktop installed

**Comment by julialawrence** [comment]
After experimenting with several approaches, our proposal for implementing this usecase for the finance team digrammed here: https://mojdt.slack.com/archives/C062MEEF5SQ/p1699457775225609?thread_ts=1699456879.652999&cid=C062MEEF5SQ

**Comment by julialawrence** [comment]
We have a meeting scheduled with the requestor to confirm the key assumptions. If those are confirmed, we will proceed to raise stories for implementation.

**Comment by julialawrence** [comment]
After a meeting with the requestor, we have agreed a way forward. Although not all users have the same level of access, a prerequisite to the chosen approach, the customer agreed to supply a "master author" who is allowed to view all data, who then will use PowerBi native capabilities to publish sub-reports with limited amount of data and distribute them.

**Comment by julialawrence** [comment]
Follow-on stories raised. Closing.
