### ISSUE TITLE
🌱 Spike: SageMaker

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1922]
### User Story

As part of our effort to offer better tooling experience both for Analytical Platform and Data Platform, we would like to investigate alternative ways of providing analytical tooling IDEs to customers. We are looking for solutions that have a good selection of features, are fairly straight-forward to maintain, easily scalable and additionally make it easier to add new tools on customer request.

As such we would like to assess AWS SageMaker as an option.

### Value / Purpose

SageMaker is a flexible managed service for providing tooling environments to customers that easily integrates into AWS IAM. it answers at least some of the requirements outlined above. We would like to understand how it stacks up against the current solution of choice: coder. 

### User Types

AP Users

### Hypothesis

If we are able to offer a more flexible scalable analytical tooling platform, we will attract additional users, not just from D&A.

### Proposal

Assess the capability, operational requirements and costs of SageMaker and compare it to coder to allow us to make a decision regarding out tooling going forward.

### Definition of Done

- [x] POC implemented 
- [ ] SageMaker assessed
- [ ] Conclusions captured
- [ ] Proposal drafted regarding tooling choice and circulated
- [ ] ADR drafted
- [ ] UR needs identified
- [ ] Follow-on stories raised

**Comment by Gary-H9** [comment]
I have created [this](https://github.com/ministryofjustice/data-platform/issues/1970) issue in relation to the build of the SageMaker MVP and [this](https://github.com/ministryofjustice/data-platform/issues/1971) ticket to make data available to it.

**Comment by Gary-H9** [comment]
PoC implemented as per [🧱 MVP: Build SageMaker in Development#1970](https://github.com/ministryofjustice/data-platform/issues/1970).

💰  Further details regarding price are included in the #data-platform-sagemaker Slack channel.

**Comment by Gary-H9** [comment]
[Discussion](https://github.com/ministryofjustice/data-platform/discussions/2155) created.
