### ISSUE TITLE
:alert: Add Alerting

### ISSUE THREAD

**Issue by Emterry** [ministryofjustice/analytical-platform#1924]
### User Story

We need some kind of metrics defined for alerting using managed prometheus and grafana to understand how our infrastructure on MP is performing. e.g CPU usage vs request, CPU usage vs limits, OOM restarts, runaway memory consumption etc.

links to issue [#1825](https://github.com/ministryofjustice/data-platform/issues/1825)

### Definition of Done

- [ ] Alert routes implemented
- [ ] Alerts defined, and tested
- [ ] Tests are green

**Comment by julialawrence** [comment]
What work? No one knows!

**Comment by Emterry** [comment]
https://github.com/ministryofjustice/analytics-platform-helm-charts/commit/92944b3a63ecb64db788319891c268d31931aa0f

documentation : https://github.com/moj-analytical-services/user-guidance/commit/d6dbbd49cde89c2bc94f3f9288ccec8a4f93c191
