### ISSUE TITLE
Control Panel SSO integration

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1938]
### User Story

We would like to be able to manage catalogue permissions via our proposed identity strategy including mapping roles to users based on groups assigned to them in the single access UI,

### Value / Purpose

Single pane of glass for managing identity allows easier uptake of the platform and makes using it a better experience as well as make it more secure. Thus integrating all our tooling into the construct is is critical in achieving this. 

### User Types

Data Platform Users & Operators

### Hypothesis

If we implement a single pane of glass identity management system, we will become more attractive to users and improve experience both for data consumers and data owners.

### Proposal

Investigate APIs for user/role assignment in the catalogue.
Complete POC using 2 kinds of roles: admin and user. All authenticated users are able to get a reader role, and those in the admin group can get admin role in teh catalogue

### Definition of Done

- [ ]  Complete a POC of linking user identity (including groups) to a catalogue role
- [ ] Fidings captured
- [ ] User Research possibilities captured
- [ ] Follow-on stories raised
