### ISSUE TITLE
🧑‍🤝‍🧑 Define Agenda for Labs & DPAT User Journey OnSite

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1945]
### User Story

We need to define an agenda and a list of outcomes for our in-person day with Labs to define the user journey via the single UI.

### Value / Purpose

We want to get the most out of a joint day and make sure that all questions are answered. Therefore, we are looking to fully define the agenda for the day so we can us the time effectively.

### User Types

DP Operators

### Hypothesis

If we have a well-laid-out agenda we will get the most out of our time. 

### Definition of Done

- [ ] Agenda fully defined
- [ ] All questions captured
- [ ] Answers to the questions captured
- [ ] Follow-on stories raised

**Comment by jacobwoffenden** [comment]
https://github.com/ministryofjustice/data-platform/discussions/1946

**Comment by jacobwoffenden** [comment]
I'm closing this discussion as this session has concluded. Actions have been raised.
