### ISSUE TITLE
✨ Add GitHub Actions workflow to redeploy existing version of an Analytical Platform RShiny app

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1982]
### User Story

As a platform engineer
I want to be able to redeploy an existing version on an RShiny app
So that I don't need to rebuild a new version of an app to see changes to the dynamic variables

### Value / Purpose

Rebuilding can cause a drift from the currently deployed version, if packages aren't correctly pinned, or a Dockerfile hasn't been updated

### Useful Contacts

Data Platform Apps and Tools

### User Types

Platform engineering

### Proposal

Create a GitHub Actions workflow that takes the currently deployed as its input

### Definition of Done

- [ ] GitHub Actions workflow is created
- [ ] GitHub Actions workflow is deployed to app repositories
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Ed-Bajo** [comment]
The worklflow for this exist - https://github.com/ministryofjustice/ap-rshiny-notesbook
