### ISSUE TITLE
🕵️ Investigate if its possible to programatically control Observability Platform Grafana

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2028]
### User Story

As a platform engineering
I want to be able to maintain Grafana configuration in code
So that we don't clickops anything

### Value / Purpose

#TeamNoClickOps

### Useful Contacts

@jacobwoffenden

### Hypothesis

If we create everything in code
Then nothing will get missed if we need to recreate, promote through envs

### Proposal

Explore connecting to AWS Managed Grafana using Terraform

### Additional Information

This looks like it might help https://docs.aws.amazon.com/grafana/latest/userguide/v9-alerting-setup-provision-terraform.html

### Definition of Done

- [ ] We can connect to AMG with Terraform
- [ ] We can provision datasources with Terraform
- [ ] We can provision teams with Terraform
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by julialawrence** [comment]
If only there were comments that explained all of this and captured the output of this story.

**Comment by jacobwoffenden** [comment]
Linked pull request https://github.com/ministryofjustice/data-platform/pull/2071
