### ISSUE TITLE
🕵️ Investigate if its possible to sync AWS IAM Identity Center groups with Grafana Teams

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2029]
### User Story

As a platform engineer
I want our tooling access to sync from our IdP
So that we don't need to manually maintain teams in Grafana

### Value / Purpose

Maintaining access in one location will remove the need for syncing users manually

### Useful Contacts

@jacobwoffenden

### User Types

Platform engineering

### Hypothesis

If we have automatic user sync enabled
Then we shouldn't need to maintain it manually

### Proposal

Teams can take an external group ID, populate with a group from Identity Center (we'll need Ops Eng to get that)
<img width="1470" alt="Screenshot 2023-10-23 at 16 55 38" src="https://github.com/ministryofjustice/data-platform/assets/15148673/40ea3384-8b43-4600-a200-dab9b8845c14">

### Definition of Done

- [ ] Team members are synced automatically
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by julialawrence** [comment]
I'm so lonely...so lonely...soooooooo lonely

**Comment by jacobwoffenden** [comment]
Linked pull request https://github.com/ministryofjustice/data-platform/pull/2071
