### ISSUE TITLE
🫂  Authorisation microservice: Design Permission Model (draft)

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2077]
### Background

This story is to design the permission models which can be used by Authorisation micro service for managing the permission for following components
 - Data sources (S3 bucket and  S3 folders within a S3 bucket)
 - APIs (Datalabs)
 - tooling 
   - Open metadata

### Scope
Focusing on the parts required by the data-product-registering flow
- The concepts of Permission Model 
  - Entity 
  - Role
  - Permission 
  - User
  - Group/Team ( A concept which can be used for managing the entity's permission easily, shouldn't be a mandatory concept) 
- The structure of Permission model (the relationships between above concepts
- Where the model be stored
  - DB --> database schema
  - Auth0 -> map them into current concept of the auth0  

### Value / Purpose

This design can be vital for implementing our IAM & Access managing strategies 

### Hypothesis

The permission model should be able to translate to the actual infrastructure IAM & Access Model e.g. AWS platform, Open metadata 

### Proposal

(Will be provided later)  RBAC + PBAC?

### Definition of Done

- [ ] Conceptual model
- [ ] Technique implementation model covering
  - [ ] Permission model data structure 
  - [ ] Decision where it should be stored (DB and Auth0)
  - [ ] The spec for the list of identified API endpoints with focusing on data-product-registration-flow
- [ ] Documentation

**Comment by Ed-Bajo** [comment]
Plan to do something else.
