### ISSUE TITLE
Migrate analytical-platform-ops repo into DP

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2137]
### User Story

We have another old repo without workflows `analytical-platform-ops` which needs to be migrated into management. This story is to achieve this.

### Value / Purpose

This will reduce the number of repos we have to manage and will allow us to update infrastructure under management there. 

### User Types

Data Platform Operators

### Hypothesis

Migrating this code into data platform repo will also allow us to do a quick review of what infra is managed there and might offer for future stories rationalising the code.  

### Proposal

Propose initial lift and shift of the code to enable changes via workflows and close monitoring.
Use the opportunity to address ALL static code analysis issues present in the code, and make it runnable on TF v1.x

### Definition of Done

- [ ] Code currently managed in `analytical-platform-ops` repository and not yet migrated into a data platform component has been migrated to the data platform repo
- [ ] All static code analysis errors and warnings are addressed
- [ ] Follow-on stories raised for rationalising the code. 
- [ ] Remove git-crypyt usage
- [ ] Access log for S3 buckets still accessible
