### ISSUE TITLE
Implement Collection of CloudWatch Logs & Metrics from Labs

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2145]
We would like to collect logs that the Labs team is shipping to CloudWatch and CloudWatch logs in order to allow them to be visualised in our managed Grafana in the observability account

## Proposal

We need to create roles that Grafana can assume in labs' MP accounts which will allow it to query CW. The roles will have similar 
permissions that are defined in data-platform-apps-and-tools-<environment>

## Potential Issues

The roles need to be defined in the `data-platform` folder in `modernisation-platform-environments` repo which isn't fully friendly to multiple people working on it at the same time. 

## Additional Info

https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/data-platform-apps-and-tools/observability-platform.tf

## Definition of Done

- [x] Set up a meeting with Labs to arrange a time when roles could be authored and deployed
- [x] Collection roles authored
- [x] Collection roles tested
- [x] Work handed over to Labs team to allow begin visualising their findings

**Comment by Emterry** [comment]
data source enabled in dev,test, and preproduction. These are the prs : https://github.com/ministryofjustice/modernisation-platform/pull/5375, https://github.com/ministryofjustice/modernisation-platform-environments/pull/3852
