### ISSUE TITLE
🪓 Split out Dependabot / PRs from data-platform-notifications

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#2149]
🚚 dependabot / PR into another channel 
Value: to see the user stories and not to get lost in the :loud_sound: of :dependabot: and :pr: 

DoD

- [x] Create another channel
- [x] Subscribe to GitHub notification and levels of (do we need to know)
- [ ] Update support [runbooks](https://runbooks.analytical-platform.service.justice.gov.uk/documentation/ways-of-working/#support-duties)

[Slack Message](https://mojdt.slack.com/archives/C04M8224WCV/p1698745455406529?thread_ts=1698745455.406529&cid=C04M8224WCV)

**Comment by bagg3rs** [comment]
Removed dependencies label from channel by running
`/github unsubscribe ministryofjustice/analytical-platform +label:"dependencies"`
`/github unsubscribe ministryofjustice/data-platform-support` this logged dependabots only, as it sends issues to support channel.

Created channel [#analytical-platform-dependencies](https://moj.enterprise.slack.com/archives/C07C9DF4Z9N) and ran
`/github subscribe ministryofjustice/analytical-platform +label:"dependencies"`
`/github subscribe ministryofjustice/data-platform-support +label:"dependencies"`
