### ISSUE TITLE
🤖 Monitor Self-Hosted GitHub Action Software versioning

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2164]
As part of this [PR](https://github.com/ministryofjustice/data-platform/commit/09f5964bc4799ec96234b1af8b78d81211fed0a5) we noted that we need to keep the self hosted GitHub Action runner up to date. In numerous places there are versions of pieces of software which we do not want to fall out of date. 

The purpose of this ticket is to identify all of these and produce a solution which, in a similiar way to dependabot, notes a version has increased / there is a delta between the code and the latest version, and raises a PR to have this updated. Ideally, as in the case of dependabot, the PR would have the code changes in it.

### Definition of Done

- [ ] Identify hardcoded versioning within the Actions Runner Dockerfile for [example](https://github.com/ministryofjustice/data-platform/blob/70aa947589c11a9886deef3614cb5547aac861b3/containers/actions-runner/Dockerfile#L15) / [example](https://github.com/ministryofjustice/data-platform/blob/70aa947589c11a9886deef3614cb5547aac861b3/containers/actions-runner/Dockerfile#L34)
- [ ] Establish a methodology for keeping this up to date. i.e. investigate if possible with Dependabot or Renovate
- [ ] If not create a custom monitoring solution
- [ ] Once the method is defined enact where appropriate

**Comment by julialawrence** [comment]
Closed as won't do as very old
