### ISSUE TITLE
🚀 Update Open Metadata to 1.2

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2175]
### User Story

As a data platform operator
I expect all our tools to be up-to-date
So that we can benefit from the upstream development efforts

### Value / Purpose

Keeping our tooling up-to-date allows us to take advantage of the features that come with new releases, in this case @ministryofjustice/data-platform-labs are keen to make use of the custom database properties

### Useful Contacts

@jacobwoffenden

### User Types

data platform operators

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Update Open Metadata to 1.2

### Additional Information

https://docs.open-metadata.org/v1.2.x/deployment/upgrade
Co-ordinate with @ministryofjustice/data-platform-labs 

### Definition of Done

- [x] Supporting resources are updated (OpenSearch)
- [x] Open Metadata is updated to 1.2
- [x] Another team member has reviewed
- [x] Tests are green
