### ISSUE TITLE
📌 Upgrade DPAT EKS cluster add-ons and platform components

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2180]
### User Story

As a platform engineeer
I expect my platform to be up-to-date
So that we don't get stuck on old versions

### Value / Purpose

Keeping EKS and platform components up-to-date should stop us getting stuck on old versions

### Useful Contacts

@jacobwoffenden

### User Types

Platform engineering

### Hypothesis

If we upgrade all the things regularly
Then we won't need to put in loads of effort at a later date upgrading everything

### Proposal

Upgrade EKS and platform components (not Open Metadata)

### Additional Information
Related to https://github.com/ministryofjustice/data-platform/issues/2167

_No response_

### Definition of Done

- [ ] EKS cluster add-ons and platform components on latest stable
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by michaeljcollinsuk** [comment]
Related ticket: https://github.com/ministryofjustice/data-platform/issues/2167

**Comment by jacobwoffenden** [comment]
EKS cluster (add-ons and nodes) upgrades have been applied to both development and production.

EKS platform components (helm charts) upgrades have been applied to development only via https://github.com/ministryofjustice/modernisation-platform/pull/5434

Moving to blocked while https://github.com/ministryofjustice/modernisation-platform/issues/5432 is looked at by MP

**Comment by jacobwoffenden** [comment]
EKS add-ons, nodes and platform components have been upgraded
