### ISSUE TITLE
🔍 Setup DPAT Alerting Routes in Alpha Grafana

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2234]
### User Story

Set up alerting routes for each team utilising Alpha Grafana so they can define and route their own alerts.

### Value / Purpose

Allows visibility of resources

### User Types

Users of Alpha Grafana

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Additional Information

Grafana -> PagerDuty -> Slack

### Definition of Done

- [ ] MVP: Alerts for us
- [ ] Create channels in Slack 
- one high priority, one low priority (* not in Terraform)
- [ ] Documentation has been written / updated
- [ ]  Configure alert rules (in Terraform)
- [ ] Configure notification policies (in Terraform)

**Comment by julialawrence** [comment]
Can't remember what this is about.
