### ISSUE TITLE
🔥 Retire and replace legacy GitHub Teams

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2242]
### User Story

As a platform engineer
I expect all GitHub teams to be up-to-date and defined in code
So that we don't allow for drift

Follow on from #1884

### Useful Contacts

@jacobwoffenden

### User Types

Platform Engineer

### Proposal

Replace all references to the following teams:

- data-platform-core-infra ➡️ analytical-platform
- data-platform-apps-and-tools ➡️ analytical-platform
- data-platform-security-and-auditors ➡️ analytical-platform-security

Remove references to the following teams:

- data-platform-tech-archs

### Additional Information

data-platform-apps-and-tools: https://github.com/search?q=org:ministryofjustice%20data-platform-core-infra&type=code
data-platform-core-infra: https://github.com/search?q=org:ministryofjustice%20data-platform-apps-and-tools&type=code
data-platform-security-and-auditors: https://github.com/search?q=org:ministryofjustice+data-platform-security-and-auditors&type=code

### Definition of Done

- [ ] Teams have been reconciled
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by AntFMoJ** [comment]
This ticket will be addressed alongside [Split out Github Component to Separate Repo](https://github.com/ministryofjustice/data-platform/issues/3044)

**Comment by AntFMoJ** [comment]
Removed Simon from data-platform-audit-and-security team, draft PR linked [here](https://github.com/ministryofjustice/data-platform-github-access/pull/9)

**Comment by AntFMoJ** [comment]
This ticket is being parked until we have decommissioned the Data Platform estate.

**Comment by julialawrence** [comment]
Closed as won't do
