### ISSUE TITLE
🔎 (Re)Enable CodeQL

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2270]
### User Story

As a platform engineer
I expect static analysis to be run across the codebase
So that we make use of GitHub's tooling to detect issues

### User Types

platform engineering

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Enable CodeQL, initially for Python

### Additional Information

It was enabled, but turned off in March

### Definition of Done

- [ ] CodeQL for Python is enabled
- [ ] Another team member has reviewed
- [ ] Tests are green
