### ISSUE TITLE
🚨 Alerting on Eventbridge

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2331]
> [!NOTE]  
> Pre-requisite: PagerDuty integrations need to be setup for Data Platform Accounts. (In the same manner that they are setup in the modernisation platform account) 

### User Story

As an engeineer on the platform
I need/want/expect to… be notified when eventbridge is not working correctly
So that… this is automated and we minimise downtime etc

### Proposal

Setup CloudWatch alarms to SNS to PagerDuty. 

Do this in Terraform. 

### Additional Information

This is related to the work done in [this](https://github.com/ministryofjustice/data-platform/pull/2274) PR. 

### Definition of Done

- [ ] CloudWatch alarms defined
- [ ] CloudWatch alarms created in Terraform 
- [ ] CloudWatch alarms tested in Dev
- [ ] SNS defined in Terraform
- [ ] PagerDuty integration defined in Terraform if required.

**Comment by julialawrence** [comment]
Reconsider after new world. To be reconsidered as part of new platform design.
