### ISSUE TITLE
⬆️  Upgrade JupyterLab to support Python >3.10

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#2348]
### Describe the feature request.

This ticket would cover the work required to release a new version of `jupyter-lab` to users running on `Python 3.10`

**Recommended Approach**:

- [x] Update the [dockerfile](https://github.com/ministryofjustice/analytics-platform-jupyter-notebook) to reflect the new base version of python
- [ ] ~Update the [helmchart](https://github.com/ministryofjustice/analytics-platform-helm-charts) accordingly~
- [x] Create a new release on control panel

**Acceptance Criteria**

- [ ] A version of `jupyter-lab` running on `python 3.10` is available to AP users

### Describe the context.

The current AP allows for the launching of several variants of `jupyter-lab`, however all of the currently available images are based on Python 3.9. However, a change to the base version of python used by Airflow has lead to [the current guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/airflow/instructions/dag-pipeline/#validate-from-the-command-line-optiona) becoming invalid, as the validation process requires a base python version of `3.10`.

### Value / Purpose

This would allow our user guidance to be applicable once more, providing a high quality of service to users. Beyond the immediate value to airflow users, keeping up-to-date versions of python available to users allows users to write code targeting newer features of base python, giving them the advantages of the continued development of the language.

### User Types

Any python users of AP.

### Definition of Done
- [ ] Complete Recommended Approach above
- [ ] Update [the current guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/airflow/instructions/dag-pipeline/#validate-from-the-command-line-optiona)

**Comment by michaeljcollinsuk** [comment]
We also need to update the python version used in the rstudio images, see message in [#ask-data-platform channel](https://mojdt.slack.com/archives/C04VBJTKY58/p1702031809409569)

**Comment by jacobwoffenden** [comment]
Stats on Jupyter image usage as of 29/01/24

```yaml
allspark-notebook:
  - v2.0.0: 4
  - v3.0.0: 36
  - v3.0.1: 41
  - v3.1.13: 131

datascience-notebook:
  - lab-3.1.12: 43
  - v3.1.13: 64
  - v3.1.14: 119

datascience-notebook-moj: # no idea where this is from
  - lab-3.1.12: 59

oracle-datascience-notebook: {}
```

**Comment by jacobwoffenden** [comment]
https://github.com/ministryofjustice/analytics-platform-jupyter-notebook/pull/76 has been merged and `v4.0.0-beta` released

**Comment by jacobwoffenden** [comment]
* `ghcr.io/ministryofjustice/analytical-platform-datascience-notebook:v4.0.0-beta`
* `ghcr.io/ministryofjustice/analytical-platform-allspark-notebook:v4.0.0-beta`

**Comment by jacobwoffenden** [comment]
Created a restricted release for datascience https://controlpanel.services.analytical-platform.service.justice.gov.uk/release/65/

**Comment by jacobwoffenden** [comment]
Release didn't work https://ministryofjustice.sentry.io/share/issue/33ff6c170bc8443481b346078b4dc951/

**Comment by jacobwoffenden** [comment]
Manually upgraded with

```bash
helm \
  --namespace user-jacobwoffenden \
  upgrade \
  --reuse-values \
  --set jupyter.image="ghcr.io/ministryofjustice/analytical-platform-datascience-notebook" \
  --set jupyter.tag="v4.0.0-beta" \
  jupyter-lab-datascience-notebook-jacobwoffenden \
  mojanalytics/jupyter-lab-datascience-notebook \
  --version 3.0.19
```

But gets stuck in `CrashLoopBackOff` with

```bash
WARNING: Use start-notebook.py instead
[W 2024-01-30 12:33:24.526 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2024-01-30 12:33:24.528 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-30 12:33:24.528 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-01-30 12:33:24.532 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-01-30 12:33:24.532 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2024-01-30 12:33:24.535 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-01-30 12:33:24.536 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-01-30 12:33:24.538 ServerApp] ServerApp.token config is deprecated in 2.0. Use IdentityProvider.token.
[I 2024-01-30 12:33:24.538 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-01-30 12:33:24.538 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-01-30 12:33:24.541 ServerApp] nbclassic | extension was successfully linked.
[I 2024-01-30 12:33:24.541 ServerApp] nbdime | extension was successfully linked.
[I 2024-01-30 12:33:24.544 ServerApp] notebook | extension was successfully linked.
[I 2024-01-30 12:33:24.752 ServerApp] notebook_shim | extension was successfully linked.
[W 2024-01-30 12:33:24.766 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 2024-01-30 12:33:24.766 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-01-30 12:33:24.768 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-01-30 12:33:24.768 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-01-30 12:33:24.777 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2024-01-30 12:33:24.778 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-01-30 12:33:24.780 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2024-01-30 12:33:24.780 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2024-01-30 12:33:24.780 LabApp] Extension Manager is 'pypi'.
[I 2024-01-30 12:33:24.782 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-01-30 12:33:24.786 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2024-01-30 12:33:24.788 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-01-30 12:33:24.830 ServerApp] nbdime | extension was successfully loaded.
[I 2024-01-30 12:33:24.832 ServerApp] notebook | extension was successfully loaded.
[C 2024-01-30 12:33:24.833 ServerApp] Running as root is not recommended. Use --allow-root to bypass.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.
```

**Comment by jacobwoffenden** [comment]
I'm parking this ticket as updating the base image is not a drop in replacement 😢 this work also blocks https://github.com/ministryofjustice/data-platform/issues/3041

**Comment by jacobwoffenden** [comment]
v3.6.3 of Jupyter Lab has been released which includes Python 3.10
