### ISSUE TITLE
⏰ Alert on secrets that are approaching expiration

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2352]
### User Story

As a platform engineer
I need to know when secrets need rotating
So that we don't incur any downtime

### Useful Contacts

@jacobwoffenden

### User Types

Platform Engineering

### Hypothesis

If we add alerts for secrets that need rotating
Then we shouldn't encounter any downtime when said secrets expires

### Proposal

For secrets that expire, e.g.:

`auth0/${TENANT_NAME}/entra-id/client-secret`

We should add a tag, maybe `secret-expiration-date: DD/MM/YYYY` and write a function that evaluates them everyday fires a PagerDuty alert 30 days before

### Additional Information

I have added a `secret-expiration-date` to `auth0/${TENANT_NAME}/entra-id/client-secret`

### Definition of Done

- [ ] Lambda fires an alert to PagerDuty when a secret is close to expiration 
- [ ] Another team member has reviewed
- [ ] Tests are green
