### ISSUE TITLE
🚸 Process & Code for Separate Image Build Repos

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2502]
### User Story

As the outcome of [this discussion](https://github.com/ministryofjustice/data-platform/discussions/2163) Data Platform engineers would like to implement a process, define a  template and provide documentation for anyone who wishes to manage their image build via a separate repo rather than using the data platform monorepo.

### Value / Purpose

The plusses and minuses of managing image builds outside the monorepo are outlined in the discussion linked in the previous section, and there is at least a minimal interest in taking advantage of this approach, 

### Useful Contacts

@julialawrence

### User Types

Data Platform Engineers

### Hypothesis

If we introduce a process as well as tools to manage repos outside DP monorepo we will minimise the issues that commonly arise out of proliferation of project repositories. 

### Proposal

1. Define a template for the image build repo
2. Define a process for creating a repo and managing it in code
3. Raise an example PR
4. Produce documentation on best end state and required controls

### Definition of Done

- [x] Docker Image build repo template defined
- [x] Process defined and documented
- [x] Example PR raised and example repo created.
- [x] Documentation updated.

**Comment by Emterry** [comment]
update intial repo added https://github.com/ministryofjustice/analytical-platform-image-build-template

**Comment by Emterry** [comment]
example repo manually created and test image built
