### ISSUE TITLE
✈️  Convert Kube2IAM roles to function with IRSA

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#2845]
### User Story

In order to run airflow jobs on the new cluster, said cluster will need to be able to assume roles existing in the AP-Data-Production account. Currently, said roles are handed in using pod annotations and Kube2IAM. However, for the new cluster it will be IRSA used to pass the roles. As such, we should experiment to find what changes are required to allow this to function seamlessly to users.

### Proposal

The person doing this ticket will need to experiment a bit, as IRSA for Airflow is a new use case. Once they are confident with the creation and passing of IRSA roles, they should then expand their scope to cover converting and existing role into one that can be assumed via IRSA.

### Definition of Done

- [ ] Experiment and build a system where two different airflow pods can assume different roles via IRSA.
- [ ] Demonstrate that said IRSA roles can be handed in from a separate account (you will likely need an assumption statement on both sides)
- [ ] Write up the steps required to convert a Kube2IAM compatible role to an IRSA compatible one.
