### ISSUE TITLE
✈️ Devise new image upload system (including image scanning)

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#2901]
### User Story

As an… Airflow Maintainer
I need/want/expect to… have users upload images to airflow that are secure
So that… I can run a platform where we are confident that user code is safe to execute.

### Value / Purpose

Users can currently upload images they build themselves, which allows users to self-service update their images while in development. In order to continue to follow best practice, we should create an image upload mechanism that surfaces security outcomes to users directly, so they can act on the information provided.

### Additional Information

[This is the current image upload mechanism](https://github.com/moj-analytical-services/airflow/blob/main/.github/workflows/sync_dags_to_s3.yaml). It functions by having repository level secrets stored in the template `r` and `python` repos, which then are available in user repositories based on this repo. This code is largely unchanged since its inception, and should be used as a reference, and not a template for the future action.

### Definition of Done

- [ ] Users are able to upload images that are accessible from within the new airflow environment.
- [ ] Images are scanned prior to upload, and any security issues of HIGH or CRITICAL status are returned back to them.
- [ ] Images with CRITICAL security issues are prevented from being uploaded to our ECR repositories.
- [ ] A decision should be made on whether to allow images with HIGH status security issues.
