### ISSUE TITLE
📌 Upgrade AP EKS

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2907]
### User Story

As a platform engineer
I expect my clusters to be up to date
So that they whither and die, or end up on extended support because 💰

### Useful Contacts

@jacobwoffenden

### User Types

platform engineering

### Proposal

Upgrade AP EKS to 1.25 and any components that require also upgrading

- analytical-platform-development (525294151996)
- analytical-platform-production (312423030077)
- analytical-platform-management-production (042130406152)

### Additional Information

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar
https://github.com/FairwindsOps/pluto - run on cluster

### Definition of Done

- [x] Cluster updated
- [x] Any components that require it are updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by BrianEllwood** [comment]
some additional info in this slack [thread](https://mojdt.slack.com/archives/C06KZLNS0GL/p1713193984758749?thread_ts=1713193795.686349&cid=C06KZLNS0GL)

**Comment by BrianEllwood** [comment]
- identify depreciated apiVersions with this [tool](https://github.com/FairwindsOps/pluto)
- adress depreciated apiVersions
- upgrade EKS in dev

**Comment by AntFMoJ** [comment]
This ticket is dependent on the the completion of [Short term accelerated compute instance](https://github.com/ministryofjustice/data-platform/issues/4120)

**Comment by jacobwoffenden** [comment]
Moving this item to blocked while https://github.com/ministryofjustice/data-platform/issues/4120 is finished

**Comment by Emterry** [comment]
https://github.com/moj-analytical-services/analytical-platform-flux/pull/1270 - cluster maintance on dev prior to urgrade

**Comment by Emterry** [comment]
This ticket is being closed as completed due to being split out into seperate components 
production - https://github.com/ministryofjustice/analytical-platform/issues/4631
Development - https://github.com/ministryofjustice/analytical-platform/issues/4618
analytical-platform-management-production (042130406152) - This upgrade is no loger needed plan to migrate out existing workflows and decommission - tickets raised here: [#4622](https://github.com/ministryofjustice/analytical-platform/issues/4622), [#4623](https://github.com/ministryofjustice/analytical-platform/issues/4623)
