### ISSUE TITLE
🔥  Decommission `analytical-platform-development` cluster

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2945]
As part of [this](https://github.com/ministryofjustice/data-platform/issues/2943) Epic the `analytical-platform-development` cluster will be decommissioned. 

- [ ] Pre-checks: ensure all functionality required for workloads available in the `data-platform-apps-and-tools-development` cluster 
- [ ] Migrate workloads to `data-platform-apps-and-tools-development`
- [ ] Post-migration: Check workloads are working correctly
- [ ] 🔥 Decommission Cluster

**Comment by julialawrence** [comment]
Will undertake as part of new platform work.
