### ISSUE TITLE
🔥 Decommission `analytical-platform-production` Cluster

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2946]
As part of [this](https://github.com/ministryofjustice/data-platform/issues/2943) Epic the `analytical-platform-production` cluster will be decommissioned. 

- [ ] Pre-checks: ensure all functionality required for workloads available in the `data-platform-apps-and-tools-production` cluster 
- [ ] Migrate workloads to `data-platform-apps-and-tools-production`
- [ ] Post-migration: Check workloads are working correctly
- [ ] 🔥 Decommission Cluster

**Comment by julialawrence** [comment]
Will undertake as part of new platform work.
