### ISSUE TITLE
🔥 Decommission `analytical-platform-management-production` Cluster

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2948]
As part of [this](https://github.com/ministryofjustice/data-platform/issues/2943) Epic the `analytical-platform-management-production` cluster will be decommissioned. 
 
- [ ] Enumerate which repos consume this infrastructure
- [ ] Create required roles and define these in the cluster which workloads will be migrated to (at the moment this is overly permissive
- [ ] Migrate workloads to `cloud-platform` - `live1`
- [ ] Post-migration: Check workloads are working correctly
- [ ] 🔥 Decommission Cluster

**Comment by julialawrence** [comment]
Will undertake as part of new platform work.
