### ISSUE TITLE
💄 Integrate visualisation MI/BI tool

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#2955]
### User Story

As a…
As an AP customer, I would like to publish visualisations based on AP data via the visualisation and dashboard tools, so that data can be viewed and disseminated. 

### Value / Purpose

The availability of a visualisation or dashboard tool will remove the need of building visualisation tools from scratch.
It will make it easier, faster and better for people to create, share and consume trusted data, metrics and insights

### Useful Contacts

@julialawrence
@Ed-Bajo 

### Proposal

During our discovery and recent reprioritisation exercises, it was identified that one of present needs of the Analytical Platform users are dashboard and visualisation tools. In addition, it was also established that there was a need to expand our tooling offerings on the platform (e.g. PowerBI, Quicksight, etc).
The team's focus is to carry out discovery to ascertain users needs and business requirements; in respect of visualisation and dashboard tools. In parallel, the team will continue to explore options to expand our tooling offerings for the AP by conducting technical spikes and proof of concept to establish the technical feasibility of integrating new analytical tools onto the platform (e.g. Quicksight, etc).Additional Information

### Additional Information
Calum's team would be leading on the strategy for visualisation and dashboard tools. We are expected to work collaboratively with his team.

AWS QuickSight already exists in the analytical-platform-data-production account. There are 40+ users in here.

### 13/03/2024 - MVP Scope:

Users can (without our interference):

* Authenticate with AP UI using their justice identity in front page
* Access and use QuickSight from within AP UI
* Have their permissions in AP/CP transfer into QS
* Make datasource available in QS
* Create dataset, analysis, dashboard
* Share dashboard with another QS user (Permissions)
* Use datasources in APDP seamlessly
* Traverse without reauthenticating between CP and AP
* Get some information about the use of QS. (API endpoint to get number of APUI users and QS datasources)
* Use some mechanism to share dashboards with users who are not AP users

### Definition of Done

- [ ] Gather business requirements in respect of dashboard and visualisation tools
- [ ] Complete dashboard and visualisation Quicksight tool proof of concept 
- [ ] Integrate identity management process and functionality for accessing the tools on the Analytical Platform
- [ ] Make recommendations on dashboard and visualisations tools to be integrated onto the Analytical Platform

### Linked Stories

- [x] #2978
- [x] #2996
- [x] #3053
- [x] #3061
- [x] #3062
- [x] #3064
- [x] #3065
- [x] #3066
- [x] #3067
- [x] #833
- [x] #3109
- [x] #3121
- [x] #3130
- [x] #3296
- [x] #3311
- [x] #3312
- [x] #3313
- [x] #3314
- [x] #3228
- [x] #3233
- [x] #3693
- [x] #3696
- [x] #3703
- [x] #3701
- [x] #3780
- [x] #3868
- [x] #3878
- [x] #3879
- [x] #3880
- [x] #3881
- [x] #3555
- [x] #3990
- [x] #3698
- [x] #4358
- [x] #4359
- [x] #4360
- [x] #4361
- [x] #4362
- [x] #4364
- [x] #4461
- [x] #4468
- [x] #4655
- [x] #4658
- [x] #4659
- [x] #4748
- [x] #4749
- [x] #4737
- [x] #4837
- [x] #4838
- [x] #4913
- [x] #5378
- [x] #5381
- [x] #5383
- [x] #5459
- [x] #5460
- [x] #5461
- [x] #5462
- [x] #5463
- [x] #5464
- [x] #5465
- [x] #5466
- [x] #5599

**Comment by DaleyDelivery** [comment]
Replaced by milestone - https://github.com/ministryofjustice/analytical-platform/milestone/9
