### ISSUE TITLE
📈 Data Platform Priorities - Large Language Model - LLM (Epic)

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#2975]
## User Story

As a Data Scientist 
I want to explore using Large Language Model (LLM), 
So that there is a secure  managed location to explore using these tools that can aid MoJ's data driven strategy. 
## Other information

The Analytical Platform currently does not have the ability to offer LLM tooling due to the limitations.

Discussion on LLM in ask channel [here](https://mojdt.slack.com/archives/C04VBJTKY58/p1691499918891869)

## Value

- provide tooling to aid our Data Science teams with technology that can speed up delivering value from our data
- reduction of repetitive manual tasks, Improving communication, entity extraction, text summaries, voice and image recognition.
- reduce teams maintenance and management by using a Managed Service offering

### Hypothesis
If we provide tooling to our data scientists
Then we can tell better stories about our data

### Proposal

Carry out a POC on integrating Bedrock onto the Analytical Platform. 

Assess the capability, operational requirements and costs of Bedrock and compare it to other tools

## Definition of done
- [ ] Integrate Bedrock (LLM) tool on to the Analytical Platform.
- [ ] Identify users for the LLM tool and gauge the performance 
- [ ] Put in place mechanism for capturing user feedback
- [ ] Consider how to integrate the identity management and access control into the tool
- [ ] Ascertain cost analysis 
- [ ] POC findings documented

### List of issues in this epic

- [x] https://github.com/ministryofjustice/data-platform/issues/1132
- [ ] https://github.com/ministryofjustice/data-platform/issues/2078

- [x] #3000
- [x] #3456
- [x] #4290
- [x] #4718
