### ISSUE TITLE
🏗️ Create a process for providing granular access to Analytical Platform data from GitHub Actions

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2976]
### User Story

As an Analytical Platform product engineer
I want to offer granular access to Analytical Platform data for users from GitHub Actions
So that we don't have to use the infrastructure roles that are extremely permissive

### Value / Purpose

User would like to access their data from GitHub Actions #2951, and the current OIDC component gives access to either `github-actions-infrastructure` or `data-engineering-infrastructure`

### Useful Contacts

@jacobwoffenden

### User Types

Analytical Platform users

### Hypothesis

If we make a process available to create scoped roles
Then we don't have to use the infrastructure roles

### Proposal

Create a new component for creating roles and policies

OR

make this process available via Control Panel

Consolidate any standalone components covering this requirements into this work, namely cjs-dashboard-app

### Definition of Done

- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by julialawrence** [comment]
I can't read gut. Ignore.
