### ISSUE TITLE
📌 Update Analytical Platform tooling images

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3002]
### User Story

As an Analytical Platform product engineer
I want Analytical Platform's tooling images to be up to date
So that our tools aren't left to rot

### Value / Purpose

Lack of scheduled patching has meant our tooling has been left to rot, the operating system image and the packaged tooling

### Useful Contacts

@jacobwoffenden

### User Types

Analytical Platform Product Engineering

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Review current Analytical Platform tooling offerings

Look at rewriting Dockerfiles

Publish from data-platform

### Definition of Done

- [ ] Tools are working as expected
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green
