### ISSUE TITLE
Remediate Trivy Alerts on Cluster Resources

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3008]
On a pull request Terraform will perform static analysis using Checkov and tfsec, however components other than `aws-analytical-platform-development-open-metadata` haven't been processed

As of 19/07/2023, the following components are;

- [ ] aws-analytical-platform-development-cluster
- [x] aws-analytical-platform-development-open-metadata
- [ ] aws-analytical-platform-management-production-cluster
- [ ] aws-analytical-platform-production-cluster
- [ ] aws-analytical-platform-data-production-openmetadata
- [ ] cloud-platform-live-data-platform-production-github-actions-self-hosted-runners

# Proposal
Run static code analysis (within the dev container) on each component in turn, then remediate or skip issues flagged

# Definition of Done:

- [ ] All warnings addressed (including remediated or skipped)
