### ISSUE TITLE
Remediate Trivy Alerts on Analytical Platform Data Production Resources

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3009]
On a pull request Terraform will perform static analysis using Checkov and tfsec, however components other than `aws-analytical-platform-development-open-metadata` haven't been processed

As of 19/07/2023, the following components are;

- [ ] aws-analytical-platform-data-production-airflow
- [ ] aws-analytical-platform-data-production-artifact-repos
- [ ] aws-analytical-platform-data-production-kops
- [ ] aws-analytical-platform-data-production-rds-s3-exports
- [ ] aws-analytical-platform-data-production-s3-glue-crawler
- [ ] aws-analytical-platform-data-production-create-a-derived-table

# Proposal
Run static code analysis (within the dev container) on each component in turn, then remediate or skip issues flagged

# Definition of Done:

- [ ] All warnings addressed (including remediated or skipped)

**Comment by BrianEllwood** [comment]
@julialawrence  To clarify id this ticket just for Trivy Alerts  or both Trivy and Checkov ?  --- ignore this Julia I am assuming checkov as that is not covered else where

**Comment by BrianEllwood** [comment]
I am currently working on aws-analytical-platform-data-production-airflow - both checkov and trivy 

I have been recording progress in the [checkov spread sheet](https://docs.google.com/spreadsheets/d/1QkAAbCNeKIW1EonTWPm9ljTy1WII_ONlw2YqFRYtI-U/edit?pli=1#gid=315304651) and [trivy](https://docs.google.com/spreadsheets/d/1sf_5kNqaXSkxPRa7Ueqjt3KlK8XfSsfY48vhKBktYHc/edit#gid=2081017074)
