### ISSUE TITLE
💔 Split out Github Component to Separate Repo

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3044]
We would like to move our Github configuration into a separate repo to make it easier for self-serve requests. 

As platform engineers, we've encountered reluctance on the part of our users to raise PRs and otherwise self-serve requests for team membership because the github component of a rather large monorepo. Although the process is isolated, there is fear that improperly made request will have ripple effects on other infra. Therefore, we would like to split out GH component into its own repo, potentially expanding it later to include other self-serve functionality.

Proposal:

Split off GH team management component into its own repository. 

Definition of Done:
 - [x] Repository created
 - [x] Dependencies to other part of the code identified and remediated
 - [x] Workflows created
 - [x] Provisioning roles updated
 - [x] Code tested and reviewed by other team members
 - [ ] Documentation for self-servicing requests updated

**Comment by BrianEllwood** [comment]
Confirm that the repo in question is data_platform
Confirm the name of the new repository 
identify the GH team management components to be moved
need more clarification about Provisioning roles updated

**Comment by BrianEllwood** [comment]
confirmed
source data-platform 
new data-platform-github-access - internal

this is the component to move https://github.com/ministryofjustice/data-platform/tree/main/terraform/github
start with teams using import to create.

**Comment by AntFMoJ** [comment]
New repo created in [this PR](https://github.com/ministryofjustice/data-platform/pull/3793).
Repo located [here](https://github.com/ministryofjustice/data-platform-github-access).

Copied `terraform/github` directory to new repo, `terraform plan` is showing no change as expected.

**Comment by AntFMoJ** [comment]
Tasks left to do:

- Create workflows
- Add devcontainer
- Add documentation for self-servicing requests updated

**Comment by BrianEllwood** [comment]
draft pr to add  workflow for repository [pr ](https://github.com/ministryofjustice/data-platform-github-access/pull/5)

**Comment by BrianEllwood** [comment]
We had  been working in two branches one for the workflow and one for the terraform we had issues with the later and the workflow failed as it was still an empty repo so we started a new branch git_hub_workflow.

in the new branch we  found out the terraform plan which had previously had no actions had multiple creates and destroys so we copied the github dir from data-platform again and the plans were then identical 2 to change ? -- remember we will have to do this again to keep the new repo in sync with data-platform until the switch over

The workflow had issues with the AWS credentials  in the draft pr so had to manually amend the role GlobalGitHubActionAccess   to include the new repo "repo:ministryofjustice/data-platform-github-access:*". this enabled the workflow to create the terraform plan

Lots of issues with the super linter that we will have to address

**Comment by BrianEllwood** [comment]
In the end we merged Jacob W's version after a session where we went through his version compared to the work we had done. We had carried forward methods/code from the mono repo which were not required in the new stand alone repo
