### ISSUE TITLE
🎨  Create terraform to provision QuickSight in the new AP account

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#3064]
### User Story

As an Engineer,
I want to create terraform,
That will provision Quicksight in the new AP account

### Value / Purpose
We need a new Quicksight instance to integrate with the AP UI, and this should be managed in code

### Useful Contacts

@julialawrence

### Additional Information

This work is dependant on ticket #xxxx  

### Definition of Done

- [ ] Create terraform to provision quicksight in the new account
- [ ] Terraform is applied 
- [ ] Quicksight instance tested in the new account

**Comment by Ed-Bajo** [comment]
Closed as duplicate and linked to ticket #3881.
