### ISSUE TITLE
🧵 Manage Quicksight S3 datasource permissions in the Analytical Platform Dashboard

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#3065]
### User Story

As an Analytical Platform user
I want to be able to access my S3 datasources in QuickSight
So I can create a dashboard with my data

### Value / Purpose

Access to QuickSight, will make it easier, faster and better for people to read data, metrics and insights.

### Useful Contacts

@julialawrence
@Ed-Bajo 

### Proposal

The new Analytical Platform needs to be able to manage S3 datasources, so that they can be enabled for use within Quicksight. Access needs to be managed dynamically based on user interactions with the AP Dashboard, which result in corresponding calls to the Quicksight API via Boto3.

When a S3 datasource is enabled for quicksight, the AP dashboard will need to:
- Update the bucket policy to allow Quicksight to access it
- Update the Quicksight IAM role to grant it access to the bucket
- Create an IAM policy that allows access to the bucket
- [Create an IAM policy assignment](https://docs.aws.amazon.com/quicksight/latest/developerguide/create-iam-policy-assignment.html) between the user(s) with access and the created IAM policy

Users should then be able to create a dataset within the embedded Quicksight using the S3 bucket as the datasource.
Initially all users that have been granted access to the S3 bucket will also have access to use it within Quicksight. However we should consider if this may need to be restricted further, such as:
- Only some users with access to the Datasource have access within Quicksight.
- Access is limited to paths within the s3 bucket

### Definition of Done

- [ ] An S3 datasource can be managed within the Analytical Platform dashboard
- [ ] A datasource admin can enable it for use in Quicksight
- [ ] All users with access to the datasource can use it to create a dataset within the embedded Quicksight
- [ ] Create follow on stories for more managing more granular S3 datasource permissions if required.

**Comment by Ed-Bajo** [comment]
This ticket will be picked after we have concluded the Lake Formation  piece.
