### ISSUE TITLE
💡 Implement backend changes to allow the AP dashboard to grant access to Quicksight

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#3066]
### User Story

As a developer,
I want the new Analytical Platform dashboard to be able to manage IAM permissions
In order to update access to QuickSight.  

### Value / Purpose

Access to QuickSight, will make it easier, faster and better for people to read data, metrics and insights.

### Useful Contacts

@julialawrence
@Ed-Bajo 

### Proposal

The new Analytical Platform dashboard will need to update IAM permissions in order to allow users to access Quicksight.
The backend will need to make boto3 calls to dynamically grant and update user access to quicksight.
Users are registered and managed in the AWS account where Quicksight runs (provisionally expected to be Analytical Platform Compute), so the Analytical Platform dashboard will need to be authorised to make calls to Quicksight in this account.

### Definition of Done

The Analytical Platform dashboard can:
- [ ] Register a user in Quicksight
- [ ] Update a Quicksight users access level (reader/author)
- [ ] Generate an embed URL for a Quicksight user

**Comment by Ed-Bajo** [comment]
Ticket needs to be reviewed based on the Identify Center piece. It would be reviewed afterwards.

**Comment by julialawrence** [comment]
Superceeded by: https://github.com/ministryofjustice/analytical-platform/issues/4658
