### ISSUE TITLE
🎨 Service Design: Map QuickSight UI Journey for Authors, Data Admins and AP Admins

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3121]
### User Story

As a…
Service Designer,  I would like to map out a user journey for different types of QuickSight users and their customers, that integrates into our current Control Panel user flow in a way that makes it easy and intuitive for users to get QS access, access QS service and grant and remove user access
So that…
When it comes time to implement changes into the Control Panel to enable QS use, the users will have the easiest experience using the new tool. Additionally, this work can be applied more broadly across multiple dashboarding offerings.

### Value / Purpose

AP Users are familiar with how Control Panel works and user flows in it, so we want to make this offering as cognitively easy for them to take up as possible. 

### Useful Contacts

alex-vonfeldmann

### User Types

AP Users and their customers 

### Hypothesis

If we make the uptake as easy as possible, we can encourage users to use our MI/BI tools instead of creating a new RShiny apps where it fits the needs of their project

### Proposal

1. Set up a demo of current functionality
2. Doument current user flow including things outside the Control Panel
3. Propose a user journey for the team to adopt
4. Jointly review findings from #3061 and integrate the user journey to agree next steps. 

### Additional Information

QuickSight imposes certain constraints in design and implementation which might impact the user journey but as far as practicable, we want to make using the service as easy as possible.

### Definition of Done

- [ ] Demo of current AP QS process scheduled
- [ ] Demo of user-facing QS process sourced (Youtube?) 
- [ ] Current AP QS process captured
- [ ] User types defined and described
- [ ] Original user story reframed and broken down into multiple stories, one for each user type's perspective
- [ ] New user journey proposed 
- [ ] Way forward agreed
- [ ] Additional service design tasks identified and raised
- [ ] Follow-on stories raised

**Comment by alex-vonfeldmann** [comment]
Draft of relevant user types to be considered in the pilot is here, needs reviewing: https://docs.google.com/document/d/1wts7BitMZcVhGg2BKkoEPpTsLnAQOEWs5ydSiJFQiyw/edit?usp=sharing

**Comment by alex-vonfeldmann** [comment]
Draft user experience for the pilot, needs reviewing:
https://docs.google.com/document/d/1gLD0VtfH-pZBXwrtNTniPbpGtsmn8oVBaSoZfVPsdQ0/edit

**Comment by Gary-H9** [comment]
Meeting with Alex tomorrow (13th Feb)

**Comment by jacobwoffenden** [comment]
Meeting happened, this work is being paused pending technical assessment by @ministryofjustice/analytical-platform
