### ISSUE TITLE
🔧 Allow Configuration of Ingress Annotations in Cloud Platform Apps

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3150]
### User Story

As an engineer, I would like to reduce the operational burden of maintaining and debugging RShiny apps by allowing customers more freedom to configure their ingresses. 

### Value / Purpose

We have had a support request from an app owner that we suspect could be fixed by allowing them to add an annotation to their ingress definition but currently, the webapp-cp helm chart does not expose that as an option. Therefore, changes like that must be applied to all customers across the board. This is undesirable. Further, this is something that needs to be done by the team when this kind of configuration is better done by the app owners. 

### Useful Contacts

@julialawrence

### User Types

App owners

### Hypothesis

If we allow more granu;ar configuration it will reduce our support overhead.

### Proposal

Amend [webapp-cp helm chart](https://github.com/ministryofjustice/analytics-platform-helm-charts/tree/main/charts/webapp-cp) to allow custom ingress annotations to be passed in values file.
Document the change

### Additional Information

Arose out of this ticket: https://github.com/ministryofjustice/data-platform-support/issues/429

### Definition of Done

- [x] Annotations made configurable
- [x] Documentation updated
- [x] Original requestor notified
- [ ] Changes tested with sample app

**Comment by julialawrence** [comment]
This isn't completed?

**Comment by jacobwoffenden** [comment]
I have:

- Published a new chart https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/736
- Published new user guidance https://github.com/moj-analytical-services/user-guidance/pull/396
- Updated original issue https://github.com/ministryofjustice/data-platform-support/issues/429#issuecomment-1952581108

**Comment by jacobwoffenden** [comment]
Feedback from support is that issue still occurs, however that is out of scope for this work and the required functionality has been delivered, therefore I will close this ticket.
