### ISSUE TITLE
✨ Implement Visual Studio Code on Analytical Platform

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3210]
### User Story

As an Analytical Platform product engineering
I want to offer Visual Studio Code as part of our suite of web based IDEs
So that our users have an alternative to Jupyter Lab and RStudio

### Value / Purpose

Our user base have been asking for Visual Studio Code for a long time, and we finally have an official feature reqeust for this (https://github.com/ministryofjustice/data-platform/issues/3137)

Delivering this would allow them to use a modern and more familiar IDE

### Useful Contacts

@jacobwoffenden

### User Types

Analytical Platform product engineering

### Hypothesis

If we make Visual Studio Code available as a tool on the Analytical Platform
Then our users will love us

### Proposal

- [x] Review ToS for hosting Visual Studio Code (https://aka.ms/vscode-server-license)
  - We do not resell it, but we do host it for our internal users
- [x] Build (scan and test) and publish image to GHCR
- [x] Build (and test) and publish Helm chart to S3 (GHCR isn't possible right now because Control Panel cannot handle charts outside of S3 without a refactor)
- [x] Make available as a new tool on Analytical Platform Control Panel

### Additional Information

@jacobwoffenden already has a working prototype of Microsoft's Visual Studio Code

### Definition of Done

- [x] ToS of Microsoft Visual Studio Code reviewed
- [x] Image published
- [x] Helm chart published
- [x] Control Panel updated
- [x] User guidance updated

**Comment by Gary-H9** [comment]
The team worked on creating a Dockerfile - listed in [this Canvas](https://moj.enterprise.slack.com/docs/T02DYEB3A/F06KC47CRGR). 

The Dockerfile creates an Ubuntu based image which installs `code` and runs this as a non-root user.

(Slack [thread](https://mojdt.slack.com/archives/C04M8224WCV/p1708002795166729))

**Comment by murad-ali-MoJ** [comment]
added terraform code to data-platform repo and created vs-core repo. here is the new [repo](https://github.com/ministryofjustice/analytical-platform-visual-studio-code)

**Comment by Gary-H9** [comment]
Work identified today which still needs to be done: 
- [ ] Check the SHASUM of the AWS CLI
- [ ] Versioning the AWS CLI
- [ ] Add test's like the ones which are done [here](https://github.com/ministryofjustice/analytics-platform-jupyter-notebook/blob/main/datascience-notebook/test/container-structure-test.yml).
- [ ] Add the github workflows

**Comment by jacobwoffenden** [comment]
Pull request merged to publish container https://github.com/ministryofjustice/analytical-platform-visual-studio-code/pull/7 🎉

**Comment by jacobwoffenden** [comment]
20/02/24 summary:
- @jacobwoffenden container built and published as `rc1`
- @Gary-H9 updated provision-user chart
- @Gary-H9 added visual-studio-code chart, is running without Auth0 proxy, port forwarding works

TODO:
 - [x] Fix priority class, maybe being overwritten by Flux 💀
 - [x] Add Auth0 proxy
 - [x] Add IRSA EKS annotation
 - [x] Clarify if SSH keys/home directories are mapped across tools, or if EFS is just persistence on a tool-by-tool basis
   - They aren't 
 - [x] Clarify if we can remove `files` folder from chart
 - [x] Create Auth0 client for VS Code

**Comment by jacobwoffenden** [comment]
21/02/24 summary:

- Chart rebased from RStudio chart
- Deployed new priority classes
  - https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/738
  - https://github.com/moj-analytical-services/analytical-platform-flux/pull/1233
- Unhardcoded RStudio from auth-proxy image https://github.com/ministryofjustice/analytical-platform-nginx-proxy/pull/31

Currently stuck due to `request to the redirect_uri path but there's no session state found` 🤷 

@michaeljcollinsuk is having a look

suggestions for tomorrow:

- Switch to non custom reverse proxy https://oauth2-proxy.github.io/oauth2-proxy/

**Comment by jacobwoffenden** [comment]
22/02/24 summary:

* no progress made on issues

**Comment by Gary-H9** [comment]
Gary to contact John D for Microsoft contact RE licensing.

Useful canvas in relation to [helm-ing in development.](https://moj.enterprise.slack.com/docs/T02DYEB3A/F06MBDMH4JU)

**Comment by jacobwoffenden** [comment]
26/02/24 summary:

- Patched NGINX proxy https://github.com/ministryofjustice/analytical-platform-nginx-proxy/pull/32
- Released VS Code and Provision User charts https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/737#pullrequestreview-1901296115
- Tested via new release of Control Panel but failed due to naming clashes
- Released patch of Control Panel https://github.com/ministryofjustice/analytics-platform-control-panel/releases/tag/v2.5.1
- There might be more, but these are the highlights

Me and @Gary-H9 aren't super users in Control Panel development, so can't progress further 😭 

TODO:

- [x] Make @jacobwoffenden and @Gary-H9 super users
- [x] Update VS Code release
  - [x] Remove `proxy.tool`
  - [x] Update custom domain to `vscode`
- [x] Figure out how to patch `provision-users` chart to 0.2.0, it contains a new VS Code job, but Control Panel development is pinned at 0.0.14
  - EDIT 28/02/24: Control Panel **will** use the latest release for **new** users, existing users will need theirs patching like this
      ```bash
      helm upgrade --install \
        --wait \
        --timeout 10m0s \
        --reuse-values \
        --namespace user-jacobwoffenden \
        --version 0.1.1 \
        provision-user-jacobwoffenden \
        ./charts/provision-user
      ```

**Comment by jacobwoffenden** [comment]
27/02/24 summary:

* Tested oauth2 proxy as a replacement for in-house proxy
  * Wanted to test a quick win, but it isn't compatible with instance idling service
  * Also it didn't work out of the box, probably a configuration issue our end

* Release updated in Control Panel to remove `proxy.tool` and set custom domain to `vscode`

* 502 error from ingress-nginx after authenticating with Auth0, indicating successful connection from ingress to tool service, but not sure where this is manifesting from

```bash
Service "user-jacobwoffenden/visual-studio-code-jacob" does not have any active Endpoint.
``` 

* If we update tool service to point at VS Code directly, bypassing authentication, it works

TODO:

- [x] ~Replace custom NGINX proxy with vanilla NGINX image, with no authentication, just to make sure our `proxy_pass` directives are correct~
  - https://github.com/ministryofjustice/analytical-platform-visual-studio-code/pull/15

Slack thread: https://mojdt.slack.com/archives/C06KZLNS0GL/p1709043748561829

## UPDATE from the evening:

@jamesstottmoj has cracked the case, OIDC conformance needed enabling on the Auth0 (this is a prime example of why we should always do things with IaC) 🎉 

~I know this is working but we should still check if the NGINX directives can be improved~

**Comment by Gary-H9** [comment]
✨  [Added first run message to terminal](https://github.com/ministryofjustice/analytical-platform-visual-studio-code/commit/4702024d1dd1837f5aaea9acf512e7da88db95b5)

**Comment by jacobwoffenden** [comment]
📝 User Guidance update 
* https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#7-set-up-visual-studio-code
* https://user-guidance.analytical-platform.service.justice.gov.uk/tools/visual-studio-code/

**Comment by jacobwoffenden** [comment]
28/02/24 summary:

* @Gary-H9 added first run notice https://github.com/ministryofjustice/analytical-platform-visual-studio-code/pull/17
* @jacobwoffenden published user guidance https://github.com/moj-analytical-services/user-guidance/pull/398
* Span beta out into #3478

This ticket remains open to track ToS with MS, maybe we should spin that out into another ticket and have delivery liaise with software/vendor management?
