### ISSUE TITLE
📛 Analytical Platform branding

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3295]
### User Story

As an Analytical Platform product engineer
I need all the branding to be consistent
So our service is simple to the user

### Value / Purpose

We have so many different touch points for Analytical Platform, that we started rebranding as Data Platform/Data Platform Apps and Tools, it got very confusing as no official comms went out to say that happened

### Useful Contacts

@ministryofjustice/analytical-platform

### User Types

Product engineering

### Hypothesis

If we get our branding and identity consistent
Then our lives might become a little bit easier

### Proposal

# Create

- [ ] Collaboration: analytical-platform@justice.gov.uk
- [ ] Collaboration: analytical-platform@digital.justice.gov.uk

# Replace

- [ ] Collaboration: analytical_platform@digital.justice.gov.uk
- [ ] Collaboration: analytical-platform-support@digital.justice.gov.uk

# Update

- [ ] TBC

# Delete

- [ ] TBC

# Track

- [ ] DNS: analytical-platform.service.justice.gov.uk

### Definition of Done

- [ ] TBC

**Comment by jacobwoffenden** [comment]
analytical-platform:
  dns:
    - analytical-platform.service.justice.gov.uk
  email:
    - analytical-platform@justice.gov.uk
    - analytical-platform@digital.justice.gov.uk
    - analytical_platform@digital.justice.gov.uk
    - analytical-platform-support@digital.justice.gov.uk
  github:
    repositories:
      - analytical-platform
      - analytical-platform-runbooks
      - analytical-platform-user-guide
    teams:
      - analytical-platform
  slack:
    - analytical-platform
    - ask-analytical-platform
    - analytical-platform-updates
  cloud-platform:
    - analytical-platform-development
    - analytical-platform-production
  modernisation-platform:
    member-unrestricted:
      # Exists already ################################
      - analytical-platform-data-development
      - analytical-platform-data-production
      - analytical-platform-data-engineering-production
      - analytical-platform-data-engineering-sandbox-a
      - analytical-platform-development
      - analytical-platform-production
      - analytical-platform-landing-production
      - analytical-platform-management-production
      - mi-platform-development
      #################################################
    member:
      - analytical-platform-compute-development
      - analytical-platform-compute-production
  auth0:
    - alpha-analytical-services
    - dev-analytical-services
  pagerduty:
    teams:
      - analytical-platform
    schedules:
      - analytical-platform
    escalation-policies:
      - analytical-platform
    services:
      - analytical-platform-production
      - analytical-platform-non-production
    status-page:
      - analytical-platform

**Comment by Ed-Bajo** [comment]
Ascertain from Service Owner:
- To Be 'Branding' for Analytical Platform

**Comment by Ed-Bajo** [comment]
Greg has given the team the go ahead to start rebranding everything back to Analytical Platform. 

However, going forward we will still be using the phrase ‘Data Platform’ to describe the wider service area that encompasses the two core services: ‘Analytical Platform’ and the ‘Data Catalogue’. 

The service area as 'Data Platform Services' (e.g. platform based services that relate to data). See attached ([image.](https://docs.google.com/document/d/1ag8h10CQZ0qPb7-s8V3vToaAd9QlCB8Wmc19jwT6ssQ/edit)

**Comment by julialawrence** [comment]
Closed as mostly done
