### ISSUE TITLE
🤔 Make decision on integrating QuickSight to the Analytical Platform

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#3296]
### User Story
As a Platform Engineer, I want to review the issues, constraints identified from the QuickSight pilot and ascertain possible technical solutions, so that I can decide whether or not to integrate the visualisation tool onto the Analytical Platform. 

### Value / Purpose
The Analytical Platform would be able to provide QuickSight in a productionised way for Analytical Platform users (if decided to provide this tool).

Useful Contacts
@julialawrence
@Ed-Bajo

### Proposal
We recently concluded the testing of key assumptions around the technical feasibility of adding QuickSight to theAnalytical Platform. 

- [x] List issues identified around QuickSight New User Experience and proposed likely solutions.
- [x] Point out issues identified with QuickSight users’ ability to create dashboards and share them with other QuickSight Users as well as proposed likely solutions.
- [x] Itemise issues identified around operations of QuickSight ,especially ‘Cross-account’ problems and proposed likely solutions.
- [x] List issues permission and security considerations as well as proposed likely solutions.

### Definition of Done

List issues identified from the QuickSight pilot
List proposed solutions for the issues identified
Recommendation made on whether to go ahead or not with integration QuickSight 
- [ ] ADR updated #3107

**Comment by Ed-Bajo** [comment]
Questionnaire was sent out to the current users and we've received 4 response.
The final analysis would be carried out on Wednesday and would be shared with the team.

**Comment by Ed-Bajo** [comment]
See attached document for the draft analysis of the QuickSight survey - https://docs.google.com/presentation/d/18QrPCOvJC78eRoMzTqzs2fiEJbMGcZcm-681-VNdaW8/edit#slide=id.p

**Comment by murad-ali-MoJ** [comment]
Alex user experience https://docs.google.com/document/d/1gLD0VtfH-pZBXwrtNTniPbpGtsmn8oVBaSoZfVPsdQ0/edit

**Comment by murad-ali-MoJ** [comment]
canvas from Gary https://moj.enterprise.slack.com/docs/T02DYEB3A/F06H90EUL9Y

**Comment by murad-ali-MoJ** [comment]
[Here](https://docs.google.com/document/d/1rHUpdF6m3GHbQejkNuxUWr9ABnOjfedrMvM-VRCxh6c/edit), we consolidate all user experiences and proposed solutions.

**Comment by murad-ali-MoJ** [comment]
What we have completed in this ticket, [here](https://docs.google.com/document/d/1rHUpdF6m3GHbQejkNuxUWr9ABnOjfedrMvM-VRCxh6c/edit):

- Finding and summarizing issues and solutions from Alex's pilot run.
- Finding and summarizing issues and solutions from the canvas created during the team's investigation of QuickSight.
- Finding and summarizing issues and solutions from the user survey run by Edwin.
- Captured the cross-account Athena demo run by Jacob HP.
- Part of the ticket especially permission and security issues captured by  #3312.
