### ISSUE TITLE
:lock: Authentication for QuickSight

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3311]
### User Story

To ensure secure access to QuickSight for analytical platform customers, we must explore authentication options. Considering the potential use of a justice identity, we aim to minimize user friction with authentication choices. This involves evaluating the feasibility of integrating SSO, conditional on the availability of justice identity for authentication.

### Value / Purpose

Implementing a seamless and secure authentication process will enhance user experience and trust in the analytical platform, encouraging more customers to utilize QuickSight for their MI/BI needs without the need to seek alternative solutions.

### User Types

AP Customers

### Hypothesis

If we implement an efficient and secure authentication system, it will lead to increased adoption and satisfaction among AP customers, supporting our goal of retaining and expanding our customer base.

### Proposal

* Investigate the use of justice identity for authentication and the implications of integrating SSO as part of the authentication process for QuickSight.
* Identity any issues around integrating QS into SSO.
* Investigate and propose an authentication mechanism for QuickSight
* Assess built-in options (SSO integration, AAD integration, internal user management) and recommend a way forward.
* Assess approach to marrying up alpha and justice identity.

### Additional Information

https://docs.aws.amazon.com/quicksight/latest/user/external-identity-providers.html
https://docs.aws.amazon.com/quicksight/latest/user/identity-management-options.html

### Definition of Done

- [ ] Evaluation of justice identity for QuickSight authentication completed
- [ ] Decision on SSO integration made
- [ ] Other approaches evaluated
- [ ] Documentation updated accordingly
- [ ] Relevant implementation stories raised
- [ ] User requirements for authentication captured

**Comment by Ed-Bajo** [comment]
Decisions made in respect of the QS identify approach.
