### ISSUE TITLE
🔑 IAM Policies Interaction with QuickSight

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3312]
### User Story

Understanding how IAM policies interact with QuickSight (QS) IAM policies is crucial for configuring access controls. As analytical platform engineers, we need to fully understand how user's IAM permissions interact with user's QS permissions, especially when creating, sharing and editing datasets that are not based on S3 datasources.

### Value / Purpose

Clarifying these interactions will ensure that our data access controls are effectively applied, maintaining data security and compliance while facilitating the appropriate level of access for users.

### User Types

AP Customers, Data Owners

### Hypothesis

By clearly defining and documenting the interactions between IAM and QS IAM policies, we will improve our data governance and security posture, leading to increased trust and compliance.

### Proposal

Investigate and document how IAM and QS IAM policies interact in various scenarios, including data source creation, data viewing, and dataset sharing.

Specifically:

 Scenarios to test:
* User has IAM permission but not QS permissions, can they see data in a shared dataset
* User has QS permissions but not IAM permissions, can they see data in a shared dataset
* Users have IAM permissions but not QS can they create datasources?
* Create a datasource / dashboard / analysis, then delete the user that created and capture what happens to those resources

### Additional Information

https://docs.aws.amazon.com/quicksight/latest/user/datasource-run-as-role.html

### Definition of Done

- [x] Clarification of how IAM and QS IAM policies interact documented
- [x] Scenarios involving data source creation and data viewing addressed
- [x] Effects of dataset sharing on data access documented
- [x] Process diagram created

**Comment by BrianEllwood** [comment]
Worked through test scenarios to S3 bucket now moving on to Athena.

**Comment by BrianEllwood** [comment]
Canvas: https://moj.enterprise.slack.com/docs/T02DYEB3A/F05K735RJV9

**Comment by BrianEllwood** [comment]
canvas document for review https://moj.enterprise.slack.com/docs/T02DYEB3A/F05K735RJV9 from == Re worked documentation ===
 onwards

**Comment by BrianEllwood** [comment]
draft PR for document in tech docs https://github.com/ministryofjustice/data-platform/pull/3606

**Comment by BrianEllwood** [comment]
still awaiting a review

**Comment by BrianEllwood** [comment]
pr merged
