### ISSUE TITLE
🔧 Management of Current QuickSight Deployment

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3313]
### User Story

Following from the fact that we will be hosting the productionised version of QS in out Analytical Platform Account we need to understand the best route to bring the current QS deployment under comprehensive management. This involves identifying used assets and engaging with users to understand their needs and experiences.

### Value / Purpose

Proper management of the QS deployment will improve efficiency, reduce overhead, and ensure that the service aligns with user needs and platform objectives.

### User Types

AP Customers, Platform Administrators

### Hypothesis

Streamlining the management of our QS deployment will lead to improved service performance and user satisfaction, supporting our goal of becoming a one-stop shop for data.

### Proposal

* Identity usage patterns and most active users - as part of this activity establish if the existing QuickSight can be deleted and make way for a fresh QuickSight using IaC.
* Conduct an audit of the current QS deployment to identify used assets
* Map out the current permissions structure
* Evaluate the pros and cons from the technical point of view of importing vs recreating (including blockers such as needing to recreate in order to grant public access to dashboards)
* Understand and attempt to import existing resources into terraform

### Additional Information

Assess as far as possible current QuickSight usage patterns, cost implications, and scalability issues to identify optimisation opportunities and potential bottlenecks.

The existing QuickSight is in `analytical-platform-data-production` in `eu-west-1`.

### Definition of Done

- [x] Audit of current QS deployment completed
- [x] Strategy for QS deployment management
- [x] Necessary implementation stories raised

**Comment by Gary-H9** [comment]
Awaiting the results of user feedback from @Ed-Bajo, more detail in  [this thread in Slack](https://mojdt.slack.com/archives/C04M8224WCV/p1707995800245889) but ultimately we need to know if we can delete the existing QuickSight instance before proceeding any further with this. |

Additionally a decision need to be made by leadership regarding the approach if the users declare that this cannot be deleted.

**Comment by BrianEllwood** [comment]
@Ed-Bajo  creating questions for users

**Comment by Ed-Bajo** [comment]
See attached document for the draft analysis of the QuickSight survey - https://docs.google.com/presentation/d/18QrPCOvJC78eRoMzTqzs2fiEJbMGcZcm-681-VNdaW8/edit#slide=id.p
