### ISSUE TITLE
:hammer_and_wrench: Designing QuickSight Production Architecture

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3314]
### User Story

As part of our evaluation of QuickSight as a MI/BI tool for AP, we need to propose an architecture for the production deployment. This involves establishing a shared responsibility model that clearly defines what is managed by our team, by the users and which changes are made via terraform vs via Control Panel.

### Value / Purpose

Creating a well-defined architecture and shared responsibility model for QuickSight will ensure that the service is scalable, secure, and manageable. It will facilitate smooth operations and maintenance, align with best practices for cloud services, and provide clear guidelines for all stakeholders involved.

### User Types

AP Customers, Platform Engineers, AP Operators, Data Owners
### Hypothesis

By designing a clear and scalable architecture for QuickSight, along with a well-defined shared responsibility model, we can streamline deployment, management, and usage processes. This will improve service reliability, efficiency, and customer satisfaction, supporting our goal of offering a comprehensive MI/BI solution.

### Proposal

Develop a detailed architecture plan for QuickSight's production deployment that includes:
- A shared responsibility model outlining the roles and responsibilities of the platform team vs users
- A clear definition of what infrastructure and configurations will be managed through Terraform vs Control Panel

### Definition of Done

- [ ] Architecture plan for QuickSight production deployment created
- [ ] Shared responsibility model established
- [ ] Terraform management strategy defined for provisioning QuickSight resources
- [ ] Control Panel role fully defined and issues captured
- [ ] Documentation and implementation stories for deploying the architecture raised

**Comment by michaeljcollinsuk** [comment]
POC implementation of embedding AWS quicksight in a new Analytical Platform dashboard UI https://github.com/ministryofjustice/data-platform-control-panel/pull/98. 

This was demoed in a meeting with the AP team and service owner on 29/2/2024 where it was agreed we would take it forward.

**Comment by julialawrence** [comment]
@YvanMOJdigital

**Comment by michaeljcollinsuk** [comment]
WIP excalidraw for Quicksight user journeys within the new AP dashboard https://excalidraw.com/#json=MQPB94vDWIDnMAafnHeUH,41N2zjH10LD6Ckhgi6nCug

**Comment by michaeljcollinsuk** [comment]
[Excalidraw to map out ideas for Quicksight in the new AP dashboard can be found via Slack](https://mojdt.slack.com/archives/C06NFN4FMNG/p1709811504859149)

**Comment by Ed-Bajo** [comment]
Further ticket raised to cover this work.
