### ISSUE TITLE
⚗️ Spike: Breakdown Analytical Platform technical infrastructure work

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#3397]
### User Story

As an Engineer, I would like to break down the Analytical Platform technical infrastructure epic, so that the team could generate a planned strategy for addressing the issue and generate stories that will allow them to deliver to the ‘definition of done’ of the epic.

### Value / Purpose

This plan will allow the technical infrastructure of the Analytical Platform to be brought up to date to serve the users and provide the right technical environment for the team to function effectively. 

### Useful Contacts

Edwin Bajomo
[Julia Lawrence](mailto:julia.lawrence@digital.justice.gov.uk)
[Richard Baguley](mailto:richard.baguley@digital.justice.gov.uk)
[Jacob Woffenden](mailto:jacob.woffenden@digital.justice.gov.uk)

### Hypothesis

If we carry out a breakdown exercise with the involvement of the team, we will be able to utilise their expertise in identifying key infrastructural changes needed for Analytical Platform and prioritising them. 

### Proposal

The uptake of the MOJ Data Strategy (Improve justice outcomes through data driven insight and innovation), and with more people even outside Data & Analysis now seeing the value of data, there were increases both in terms of sheer numbers of users, user types and features our users want to see.

In addition, there is a need to scale up the Analytical Platform in order to meet user needs and to enable the team to have an up to date technical environment to work. 

### We are seeking to address the following:
- Revert back to wholesale Analytical Platform branding
- Reduce the engineering burden of managing multiple EKS clusters on different versions with different deployment methodologies
- Rely on Managed Services provided by AWS to help leverage their documentation / development cycles 
- Address the EKS issues
- Develop and implement ‘One User Identity’ strategy that is integrated with Entra ID Single identity for Justice
- Meet user needs and requests in respect of the Analytical Platform
. Offer better Integrated Data Environments (IDEs - VS Code  https://github.com/ministryofjustice/data-platform/issues/3210) 
. Update Analytical Platform guidance
. Agree documentation technology, location, etc
. Agree the support process  
. Integrate Large language Models (LLM) capabilities
Bedrock 
Foundation models

### Definition of Done

- [ ] Dependencies, blockers and priorities identified
- [ ] Where possible, plan of delivery drafted
- [ ] Stories raised (some may already be in the backlog)
