### ISSUE TITLE
✈️  Allow extended duration for Airflow Roles as an optional flag

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#3398]
### User Story

As a… user of airflow
I need/want/expect to… have a role with a greater duration than one hour
So that… I can do extended deployments without having to refresh my credentials.

### Value / Purpose

In conversations with @PriyaBasker23 and @mshodge previously, they've highlighted the desire for an extended role duration for their airflow role, in order to avoid timeout issues they're experiencing. In the code, we only limit to 1 hour because this is the default duration on a created role. As such, we should allow a user to pass an optional flag to extend their role session duration to a specified length. This change should NOT retroactively affect existing policies, and should only be applied to new policies featuring the flag.

### Useful Contacts

@jhpyke

### Proposal

1. Allow for passing of `role_duration_seconds` as a argument in a Role `.yaml` file.
2. This argument should be respected by the role builder, and should cause the specified duration to be applied.
3. This change should only apply to those who opt in with the argument. Those who fail to supply this argument should continue to default to a role assumable for 1 hour.

### Definition of Done

- [ ] Users can configure role session duration for airflow roles
- [ ] User docs reflect new flag and it's usage
- [ ] Existing roles are unaffected

**Comment by AntFMoJ** [comment]
The changes have been implemented to add `role_duration_seconds` to airflow roles: https://github.com/moj-analytical-services/airflow/pull/2920

Additionally updated `iam_schema.json` to include the new field: https://github.com/moj-analytical-services/iam_builder/pull/57

Added field to `airflow_dev_offender.yaml`: https://github.com/moj-analytical-services/airflow/pull/2924

Waiting for review from users to confirm these changes have been resolved their issue.

**Comment by AntFMoJ** [comment]
Received confirmation from user the ticket can be closed as complete.
