### ISSUE TITLE
🧪 VS Code beta

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3478]
### User Story

As a Analytical Platform product engineer
I want to launch a ~private~ beta
So that we can iron out any bugs, improve documentation, or add features

### Value / Purpose

This is the first major feature that Analytical Platform have released for a while, so we're trying to do it in a proper phased way

### Useful Contacts

@jacobwoffenden

### User Types

Analytical Platform product engineering

### Hypothesis

If we release VS Code to a select group of Analytical Platform users
Then we can gather feedback, squash bugs, improve documentation

### Proposal

Run a month long beta for VS Code, release to select group of Analytical Platform users

### Additional Information

Follows on from #3210

[VS Code Beta Rollout Google Sheet](https://docs.google.com/spreadsheets/d/1t__Ewn-8qzOrKrnyIP-IpEPjpCZ3t8jwMKBCKpEg6lY/edit?usp=sharing)

```bash
helm upgrade --install \
  --wait \
  --timeout 10m0s \
  --reuse-values \
  --namespace user-${USERNAME} \
  --version 0.1.1 \
  provision-user-${USERNAME} \
  ./charts/provision-user
```

### Definition of Done

- [x] Slack channel created [`analytical-platform-vscode-beta`](https://moj.enterprise.slack.com/archives/C06LY2MEGBX)
- [x] Users added
- [x] `provision-user` chart patched for `0.1.1` for users
- [x] VS Code released via Control Panel Production to users
- [ ] Feedback gathered
- [ ] Any bugs squashed
- [ ] Documentation improved

**Comment by jacobwoffenden** [comment]
28/02/24 summary:

* Users added to Slack channel
* Users added to Google Sheet
* v2.5.1 of Control Panel released to production https://github.com/moj-analytical-services/analytical-platform-flux/pull/1239
* provision-user chart patched to `0.1.1` for @jacobwoffenden
* Unable to deploy VS Code, times outs in the Control Panel UI
  * https://ministryofjustice.sentry.io/issues/4027337775/?project=5606313&query=is:unresolved&statsPeriod=14d&stream_index=1
  * https://ministryofjustice.sentry.io/issues/4027343292/?project=5606313&query=is:unresolved&statsPeriod=14d&stream_index=0

**Comment by jacobwoffenden** [comment]
Fixed deployment issue in production via https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/740

**Comment by jacobwoffenden** [comment]
29/02/24:

* Fixed deployment issue in production via https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/740
* Issue found in provision-user charts for `anthonycody`, `phil-hall-moj` and `robinl`. They `efs-sc` set in the EFS PVC, but the chart doesn't have that, so we manually amended to chart with it to patch these users

The script we used: 
```
#!/bin/bash

usernames=("user1" "user2")

for USERNAME in "${usernames[@]}"
do
  helm upgrade --install \
    --wait \
    --timeout 10m0s \
    --reuse-values \
    --namespace user-${USERNAME} \
    --version 0.1.1 \
    provision-user-${USERNAME} \
    ./charts/provision-user
done
```

**Comment by Gary-H9** [comment]
Tagging @YvanMOJdigital in relation to User Research resourcing.

**Comment by Gary-H9** [comment]
Added Priya + Michael Hodge to beta. Noted in google sheet. Updated provision-user charts for both users.

**Comment by Gary-H9** [comment]
Added a number of users to the Private Beta, will include names here when I have them. Update Google Sheet.

**Comment by jacobwoffenden** [comment]
12/03/24 summary:

- https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/741
- https://github.com/ministryofjustice/analytical-platform-visual-studio-code/pull/26

13/03/24 summary:

- https://github.com/ministryofjustice/analytical-platform-visual-studio-code/pull/27
- https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/742
- https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/743

**Comment by Gary-H9** [comment]
Add two more users. Updated sheet.

**Comment by Ed-Bajo** [comment]
Carry out user research on the release of the VS Code.
