### ISSUE TITLE
🔐 ITHC Prep

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3479]
### User Story

As a AP engineer, I need to prepare for the ITHC that will be carried out on the platform on from March 4th to March 11th.

This includes completing the project planner, onboarding users to our AWS environment and Dev/Prod control Panel. Add them to the `moj-analytical-services` GH org and make sure their access is functiional.

### Value / Purpose

Our ability to carry out this activity successfully will reflect in the quality of the outcomes we get, 

### Useful Contacts

@julialawrence

### Definition of Done
- [x] Add PenTester Roles to AP Dev Cluster 
- [x] Testers added to `moj-analytical-services` Org
- [x] IAM users created in the landing account
- [x] Roles created in the `analytical-platform-development` account with Admin access
- [x] Roles created in the `analytical-platform-data-production` with ReadOnly and SecurityAudit access
- [x] Roles exclude PNC data from visibility
- [x] Dev Control Panel users created/auth confirmed
- [x] Prod Control Panel users created/auth confirmed
- [x] User level in prod CP: User
- [x] User level in dev CP: Admin
- [x] Comms channel agreed
- [x] Standup scheduled
- [x] Leadership briefed
- [x] Team briefed
- [x] Story to cover support raised
- [x] Project Planner confirmed

**Comment by julialawrence** [comment]
Waiting on Github usernames.

**Comment by julialawrence** [comment]
Four github users added to prod (2 promoted to superadmin)
Four github usernames added to dev (2 promoted to superadmin)
