### ISSUE TITLE
🔍 Review ToS for Visual Studio Code Server

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3497]
### User Story

As a Analytical Platform product engineer
I want clarification on our usage of Visual Studio Code Server for our use on Analytical Platform
So that we don't get a scolding from Microsofy

### Value / Purpose

Analytical Platform product engineering have reviewed [Visual Studio Code Server's ToS](https://code.visualstudio.com/license/server) and we think we're OK based on this:

> General. You may use any number of copies of the software with Microsoft Visual Studio Code to develop and test your applications. You may not use the software if you do not have a license for Microsoft Visual Studio Code. Further, you may install, use and/or deploy any number of copies of the software on computer devices within your internal corporate network to design, develop and test your applications. Use of the software copies deployed through your internal corporate network are governed by the terms of this agreement.

We host Visual Studio Code Server on our internal network for use by MoJ employees, we do not make this software available commercially.

### Useful Contacts

@ministryofjustice/analytical-platform

### User Types

Analytical Platform product engineering

### Hypothesis

If we liaise with software licensing from MoJ Corporate and Microsoft
Then we can confirm that our use case is covered by the license

### Proposal

We (Analytical Platform) engage with software licensing teams to confirm we are OK to use Visual Studio Code Server on Analytical Platform

### Additional Information

This ticket follows on from https://github.com/ministryofjustice/data-platform/issues/3210

### Definition of Done

- [ ] External teams identified
- [ ] External teams engaged
- [x] Our use case vs. MS license clarified
- [ ] ADR created?

**Comment by Ed-Bajo** [comment]
Action - Get in touch with Microsoft to ascertain if our use case is covered by our license?

**Comment by jacobwoffenden** [comment]
Had a meeting with Microsoft's representative for app innovation in the public sector, however this isn't a product question, so action on Microsoft's side was to refer this ticket to their legal department, however Microsoft's representative mentioned we aren't the only UK Gov department to do this.

Moving to blocked pending response, however we do not have this action on paper.

**Comment by EO510** [comment]
Haven chased severally, I will now be adding this to our risk register for Leadership to make a decision on this

**Comment by EO510** [comment]
Microsoft got back, this request has now been moved to support and Dom from support got back on 19/06 to say he was looking at it and will get back

**Comment by EO510** [comment]
Microsoft got back on 25/06/24 “Please note that Microsoft should not provide legal advice/guidance to customers. Customers should do their own assessment and/or hire external counsel for legal advice or work with their own legal teams on whether their use-case is within the terms of the license and compliant.”

**Comment by EO510** [comment]
I reached out to our Legal team on 28/06/24 but I am yet to hear back from them

**Comment by EO510** [comment]
Our legal team reached out on Monday 15/07/24  to say he is checking with our reseller to see if this is something that they can help with.

**Comment by EO510** [comment]
A representative of the reseller - TrustMarque got back today 23/07/24 with this message 

As discussed I agree with your reding of the eula below, the Visual Studio Code is a open source software that can be used as described below.

 

This link I quite useful for additional FAQ’s.

 

[Visual Studio Code Frequently Asked Questions](https://code.visualstudio.com/docs/supporting/faq)
