### ISSUE TITLE
:building_construction: Implement Control Panel Changes for S3 Policy Management

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3693]
### User Story

we would like to apply access changes initiated by datasource admins in the Control Panel simultaiously to user roles' inline policies and separate customer-managed policies created in the account where our new QuickSight will be managed. 

### Value / Purpose

we need two sets of policies to manage QuickSight effectively: ones that govern users' permissions in the AWS environment and a duplicate which constrains their permissions in QuickSight. Doing both at the same time avoids drift. 

### Useful Contacts

Michael Collins, James Stott, Julia Lawrence

### User Types

AP Users, QS Users

### Hypothesis

If we only manage changes in one place, we will avoid differences in user access from within the AWS environment including tooling and QuickSight.

### Proposal

Amend Control Panel Code (old? new?) to do the changes simultaniously.

### Additional Information

As QuickSight and data don't live in the same account, reusing policies is unfortunately isn't possible. The next best thing would be to manage changes to them simultaneously and only in one place. Though this still doubles the number of policies we have to manage per user, most of that overhead should be abstracted away by managing this in code and in one place. 

### Definition of Done

- [ ] Proposal or an alternative agreed
- [ ] Any scope changes to the MVP are agreed and captured
- [ ] Control Panel changes implemented
- [ ] Follow-on stories raised
