### ISSUE TITLE
:package:  Capture the QuickSight 'As Is' and 'To Be' user journey

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#3696]
### User Story

As the Product Manager, I would like to capture the current and future QuickSight user journey, so that I could identify the key changes and improvements to the offering of the tool on the Analytical Platform.  

### Value / Purpose

The user journey map would help identify the value added to QuickSight users This plan will allow the technical infrastructure of the Analytical Platform to be brought up to date to serve the users and provide the right technical environment for the team to function effectively. 

### Useful Contacts

[Edwin Bajomo](mailto:edwin.bajomo@digital.justice.gov.uk)  
[Julia Lawrence](mailto:julia.lawrence@digital.justice.gov.uk)
[Alex von Feldmann](mailto:alex.vonfeldmann@digital.justice.gov.uk)

### Hypothesis

If we capture the current and future user journey, we will be able to identify the key improvements the new QuickSight tool offering would provide to Analytical Platform users.   

### Proposal

Service Designer will use the information gathered by the team from the QuickSight pilot to produce the ‘As is’ and ‘To Be’ user journey map’. 

In addition, the 'To Be' user journey map would be used to design the user interface. 

### Definition of Done

- [ ] Production of the ‘As Is’ user journey map. 
- [ ] Production of the ‘To Be’ user journey map.
- [ ] The output of the work should be consumable for the team to action.
