### ISSUE TITLE
🚀 Deploy the Analytical Platform UI in a development account

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3698]
### User Story

As a… developer
I need to… be able to deploy the AP dashboard
So that… I can test features and share with the whole team

### Value / Purpose

We need a deployment process in place as a prerequisite to future development

### Useful Contacts

@michaeljcollinsuk @jamesstottmoj @jacobwoffenden

### User Types

developers, engineers

### Hypothesis

A clearly defined deployment process will help us release features faster

### Proposal

Deploy the new analytical platform dashboard in a development account. Until the new accounts are setup, this may need to be deployed in an existing account e.g. analytical-platform-development.

Initially we will deploy an MVP of the dashboard with a frontpage as a minimum.

Deployments should handled via Github Actions. The [existing workflow files](https://github.com/ministryofjustice/analytical-platform-dashboard/tree/main/.github/workflows) may need replacing or updating.

We also need to define the release process for deploying to production in future.

QUESTIONS
- Should merging to main branch trigger a dev deployment?
- How will releases to production be managed?

### Definition of Done
- [x] Jacob demoes the deployment process
- [x] Github actions workflows defined to handle a development deployment
- [x] AP dashboard is deployed to a development environment
- [x] Documentation written to detail the deployment process
- [x] Release process is defined

**Comment by michaeljcollinsuk** [comment]
Created a related ticket to refactor the AP UI codebase https://github.com/ministryofjustice/analytical-platform/issues/4581

**Comment by jacobwoffenden** [comment]
Completed in conjunction with https://github.com/ministryofjustice/analytical-platform/issues/4456
