### ISSUE TITLE
:passport_control: Spike - Create an IAM role that we can assign to users in Quicksight

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3780]
### User Story

As a AP Quicksight user
I need an IAM role
So that it can be assigned to me when I am created as a user in Quicksight

### Value / Purpose

When we create a user in the new Quicksight, we can do so using an IAM role. Rather than every user requiring a role, we can have a generic role that is used for all users.

By using an IAM role to register a user, it removes extra signup/login steps such as creating a password

### Useful Contacts

@michaeljcollinsuk @julialawrence

### User Types

New AP UI users that will be granted access to Quicksight

### Hypothesis

If we... create a single IAM role for Quicksight users
Then... we reduce the number of individual roles we need to maintain

### Proposal

First we need to confirm that using a single role, rather than a role per user, will fit our use case. Some considerations:
- How will this effect IAM policy assignments in quicksight? E.g. need to check that these are created as a user/group to policy relationship, rather than a role to policy relationship.
- Confirm that creating users with the same role is successful when making the call via Boto in the AP UI

After confirming the above, we then need to define the permissions and trust policy the role will use. We will want to create/manage it via terraform, then use the role ARN when creating a uservia the new AP UI.

### Definition of Done

- [ ] Confirm that a single role for all QS users if viable for our use case
- [ ] Define the role permissions
- [ ] Create the role

**Comment by Ed-Bajo** [comment]
Agreed a different approach.
