### ISSUE TITLE
⚗️ Investigate RAM Sharing of Glue Catalogue into MP Compute Account

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3880]
### User Story

DataZone relies on RAM share for provision of access under the hood and we would like to investigate this approach for QuickSight making access easier in scenarios cross account.

### Value / Purpose

This not only would make the user experience better when working with data directly outside QS but also potentially be used as a test-bed of the multiple account strategy.

### Useful Contacts

Richard Baguley, Julia Lawrence

### Hypothesis

If we're able to RAM Share the Glue Catalogue we potentially could simplify the process of migrating out of Ireland altogether

### Proposal

1. Successfully RAM share Glue Catalogue into another account
2. Identify components that need to be created in the target account to support this
3. Develop Terraform code to accomplish this in MP

### Definition of Done

- [ ]  Glue Catalogue Shared
- [ ] Components Identified
- [ ] Terraform code written
- [ ] Follow-on stories raised

**Comment by julialawrence** [comment]
OBE'd in favour of Lake Formation
