### ISSUE TITLE
🔐 Implement Automated Rotation of AzureAD credentials

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3990]
### User Story

As Analytical Platform admins, we would like to implement an automated process for rotating EntraID client secrets so we do not have to manage it manually.

### Value / Purpose

Automated process is preferable and less error prone than manual. Additionally in an event of a security incident requiring rotation, it can be achieved easier.

### Hypothesis

Automating the rotation will allow is to easily and frequently rotate credentials.

### Proposal

You can define a lambda function to rotate secrets manager secrets and write them back into SM
https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html

We should utilise this template to rotate our AzureAD creds. 
The rotator function will will create a new secret, load it into secrets manager and delete the old
For its own creds, it will create a new version of its own secret, then reauth using the new creds and delete the old.

### Additional Information

This will require an app with enough permissions to do app secret rotation. This request will block this story

### Definition of Done

- [ ] Lambda function created
- [ ] Lambda function tested
- [ ] Schedule of rotation agreed
- [ ] Location of secrets manager agreed
- [ ] Deployment code written
- [ ] Function deployed
- [ ] Team reviewed
- [ ] Docs updated
