### ISSUE TITLE
🐳 Split Image Builds from Data Platform Repositories

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4004]
### User Story

To streamline the contents of our main repository, we would like to split out our container image builds into their own repositories.

### Value / Purpose

This will simplify our image releases as well as provide a cleaner release history. 

### Useful Contacts

Jacob Waffenden, Gary Handerson

### Hypothesis

If we do this, it'll be easier to track and maintain our images.

### Proposal

The proposal refers only to the following images:

* https://github.com/ministryofjustice/data-platform/tree/main/containers/actions-runner
* https://github.com/ministryofjustice/data-platform/tree/main/containers/alpine-base
* https://github.com/ministryofjustice/data-platform/tree/main/containers/kubectl
* https://github.com/ministryofjustice/data-platform/tree/main/containers/rshiny All versions
* https://github.com/ministryofjustice/data-platform/tree/main/containers/rshiny-open-source-base
* https://github.com/ministryofjustice/data-platform/tree/main/containers/rstudio
* https://github.com/ministryofjustice/data-platform/tree/main/containers/static-assets
* https://github.com/ministryofjustice/data-platform/tree/main/containers/ubuntu-base

1. Review the image builds above and determine if all of them are still needed. 
2. Using terraform, create new repositories for images we are retaining, using https://github.com/ministryofjustice/analytical-platform-image-build-template as a template 
3. Migrate the relevant code to the appropriate repo following the model of https://github.com/ministryofjustice/analytical-platform-jml-report 
4. Test the build
5. Remediate mistakes
6. Using github code search, identify and capture all references to the images we are migrating and record it in a spreadsheet.
7. Raise follow-on stories to amend references to images to their new repositories. 

### Definition of Done

- [x] Review of current images complete
- [x] New repos created
- [x] Code migrated
- [x] Build and lint workflows are green and image is building
- [x] References to images identified
- [x] Follow-on stories raised to change references to new image locations
- [x] Documentation updated

**Comment by AntFMoJ** [comment]
We have reviewed the image builds currently in use and begun creating repos in data-platform-github-access accordingly.

PR in data-platform-github-access to create image build repos is [here](https://github.com/ministryofjustice/data-platform-github-access/pull/16).
PR in analytical-platform-actions-runner to migrate image build from data-platform is [here](https://github.com/ministryofjustice/analytical-platform-actions-runner/pull/7).

**Comment by AntFMoJ** [comment]
**Question**: What documentation needs to be updated for: `actions-runner`, `kubectl`, `rshiny-open-source-base` and where can we find it?

**Comment by BrianEllwood** [comment]
updated the only refrence we could find in the documentation.
