### ISSUE TITLE
🛩️ Refactor `iam_builder` for terraform

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4290]
### User Story

As a AP ops engineer, I would like to refactor [iam_builder](https://github.com/moj-analytical-services/iam_builder) python script into terraform in preparation for migrating airflow into Modernsation Platfortm.

### Value / Purpose

For a long time, terraform lacked effective tools for managing iam policies at scale outside templating. However, in the last 4 years, many additional tools have become available, making dynamic iam policy generation straight-forward to manage. As terraform is the preferred infra-as-code tool for P&A and we have begun work to migrate airflow code into terraform, it would make a lot of sense to do the same for this component.

### User Types

@julialawrence

### Hypothesis

It will be easier to make changes to airflow policies to meet usecases such as [this](https://github.com/ministryofjustice/data-platform/issues/4222) if we provided an alternative way of generating policies for airflow without necessarily having to use python or integrating it into terraform as it is. 

### Proposal

Refactor (or extend if retirement is currently not possible) iam_builder into terraform. Although [this example](https://github.com/ministryofjustice/data-platform/blob/main/terraform/aws/analytical-platform/oidc/configuration/assumable-roles.json) is far from the most elegant, we already use terraform to generate policies from json so this would not be entirely new for the team. 

Details of the proposal:
Impement iam_builder capability in terraform in this repository and use existing examples of generated policies to test output against expectation. In order to make future transition as smooth as possible, the desired outcome is full functional parity. Any deviations need to be taken up in a follow-on story along with required design conversations.

A conversation regarding whether the implementation is using flat files or wrapped into a module should be part of this story.

### Definition of Done

- [ ] Decision on flat vs. module agreed
- [ ] iam_builder code implemented
- [ ] New iam_builder tested against existing policies and findings captured
- [ ] Assessment on how far it moves the team towards delivery of bedrock on Airflow done
- [ ] Assessment findings captured and follow-on stories raised
- [ ] Documentation updated
