### ISSUE TITLE
📖 Implement terraform modules for sharing Athena resources via Lake Formation

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4358]
### User Story

As an AP Engineer, I would like to implement terraform for sharing named Athena resources across accounts and regions, in a similar way that the Observability Platform bootstraps new accounts.

### Value / Purpose

The purpose of these module is to make adoption of lake formation for sharing resources simple for data producers. As for am immediate need, this will enable Lake Formation for managing resource access both for DPR and for QuickSight. 

### Useful Contacts

@julialawrence

### Hypothesis

If we create easily reusable modules for sharing Lake Formation resources, adopting it as an alternative to the current means of data sharing and access management will become simpler.

### Proposal

Implement (a) terraform module(s) that do(es) the following:
* Registers a data location in Lake Formation
* Shares a database/table across accounts via named resource or tags approach
* Shares a database/table resource across regions via named resource or tags approach
* Designates an admin

### Additional Information

Sharing resources with/from MP member account will also require tweaking deployment permissions for the github role used in MPE repository. Configuring the role with correct permissions _is in scope_ for this story.

### Definition of Done

- [x] Tags/Named resources approach agreed
- [x] Decision made regarding one or two modules
- [x] MPE deployment role permissions updated
- [x] Terraform module(s) implemented
- [ ] Sharing MP --> APDP and APDP --> MP tested
- [ ] Sharing London --> Ireland and Ireland --> London tested
- [ ] Final boss (Cross-acct, cross-region) tested
- [ ] Documentation updated
- [ ] Follow-on stories raised
- [ ] Functionality demoed at AP S&T

**Comment by Gary-H9** [comment]
We cannot add Localstack testing in the same manner that the observability [module](https://github.com/ministryofjustice/terraform-aws-observability-platform-tenant) uses it. This is because the "[Lake Formation](https://docs.aws.amazon.com/lake-formation/latest/dg/aws-lake-formation-api.html) is supported by LocalStack only in the pro image."

**Comment by Gary-H9** [comment]
Successfully ran through the Cross-Account Named Resource after receiving guidance. Then used this experience to review [document](https://docs.google.com/document/d/1bMk5onKLs1RC8oOXjLhlmAu84ZilAdxanvd7AAWqDRY/edit?usp=sharing) - added/made headings uniform, added title, contents. 
- Added screenshots where they were missing. 
- Added details around adding a table
- Added specifics on populating S3 bucket, what the contents should be and the inclusion of a schema
- Added comments and moved sections where needed
- Added section on testing with Athena

**Comment by Gary-H9** [comment]
✅ - The branch [lf-gary-test](https://github.com/ministryofjustice/analytical-platform/pull/4935) contains detailed description of successful cross-account, cross-region testing using the [terraform-aws-analytical-platform-lakeformation](https://github.com/ministryofjustice/terraform-aws-analytical-platform-lakeformation/tree/main) module. This does not test sharing tables. 

✅ - The branch [lf-gary-test-2](https://github.com/ministryofjustice/analytical-platform/pull/4937) contains detailed description of a WIP cross-account testing using the [terraform-aws-analytical-platform-lakeformation](https://github.com/ministryofjustice/terraform-aws-analytical-platform-lakeformation/tree/main) module. This does not test sharing tables.

**Comment by Gary-H9** [comment]
Testing in both branches above now completed. Moving on to test with the inclusion of sharing tables.

**Comment by Gary-H9** [comment]
Closing post intensive testing in conjunction with the UI work today. local-exec or external functionality can be defined and added in later tickets if required.
