### ISSUE TITLE
📖 Implement User Onboarding to QS

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4360]
### User Story

Even with Lake Formation, onboarding a user isn't straight-forward and needs to be managed across multiple accounts/regions entities at once. Therefore, we need to implement a self-serve way of onboarding a user to QS.

### Value / Purpose

Even in MVP, users should be onboarding themselves to QS.

### Useful Contacts

@julialawrence @michaeljcollins @jamesstott

### Hypothesis

QS uptake will be higher and ops overhead will be lower if we implement a one-stop onboarding 

### Proposal

The process for onbording a user is roughly this:

```
So we want to onboard an AP user to QS:
* Need a GH group with all AP users with permissions in database-access(Assumption: Only AP users with database access will have access to QS for MVP. Apps out of scope)
* Users’ DB access permissions replicated into lake formation
* Users' AP identity is mapped to IC identity (Github for now)
* Need a way to keep those permissions synced
* Register data locations in lake formation
* Share databases/tables into APCompute accounts (London)
* Assign permissions to QuickSight users
```

### Additional Information

Couple of important things on sequencing:
* We need embedding because we need to know when a user first accesses QS. We can’t assign permissions to the user’s QS user before the user exists therefore without embedding, we’ll need some way of being notified that the user has signed up and action permission granting. Otherwise it’s a two-step process with potential support request
* Why we need a common permissions interface: We can assign permissions to a IAM principal cross account (meaning LF in APDP can grant permission to a role in another account from the source account directly) but this option is not available for QS users. Meaning that granting QS permissions needs to happen in the same account as the QS lives. This means the process for permissions management could potentially span two or more accounts which isn’t ideal. Single UI (CP or APUI) will make this seamless.

This is very heavily a development task because with exception of registering and sharing existing data sources upfront, this needs to happen dynamically in response to user actions. 

### Definition of Done

- [ ] User accesses QS for the first time and their permissions are identical to AP/Database-access ones
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Follow-on stories raised
