### ISSUE TITLE
📖 Register Assets Managed in `database-access` in Lake Formation & Share them into AP Compute

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4361]
### User Story

In order to support QuickSight MVP work, I would like to make assets currently managed via `database-access` repository available for use in QuickSight in Analytical Platform Compute account

### Value / Purpose

This will support our MVP work by giving users access to datasources that based on current usage of QuickSight, the users are most interested in visualising

### Useful Contacts

@julialawrence

### User Types

Data Engineers, Data Scientists

### Hypothesis

If we provide an opportunity for close-to-production data access, we can more accurately draw conclusions about usage for Alpha and Beta

### Proposal

* Review and document the current process for managing database access in the `database-access` repo
* Identify datasources managing in the `database-access` repo
* Using the new terraform module, register and share them into the AP Compute account account

### Definition of Done

- [ ] Databases/Tables are available in the AP Compute account
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Demoed at the AP S&T
