### ISSUE TITLE
📖 Design and Implement a mechanism for syncing permissions between AP Compute for QS and `database-access`

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4362]
### User Story

Changes to the `database-access` repo **must** be reflected in LF for QS access. We can't rely on Hybrid mode for this because QS users are different principal entities to IAM roles.

### Value / Purpose

Data Engineers should be able to manage permissions in one place during the migration period.

### Proposal

One potential solution is embedding a terraform component into the database-access repo that runs when permissions are updated. 

### Additional Information

Managing syncing both ways is out of scope for this story

### Definition of Done

- [ ] Permissions in `database-access` reflect in Lake Formation in AP Compute account in real time
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Demoed at AP S&T
