### ISSUE TITLE
📖 Update Documentation and DIagrams for QuickSight to reflect new approach

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4364]
### User Story

Our approach to QuickSight has undergone some substantial revisions in light of identity and Lake Formation work. Our documentation regarding the approach and the architectural diagrams all need to be updated to reflect our current work.

### Value / Purpose

We all need to be on the same page regarding what we're building

### Useful Contacts

@julialawrence @michaeljcollins @jamesstott @bagg3rs

### Hypothesis

We're more likely to build something good if we are all know what we're building.

In a project with many moving parts, success is impossible without a common document explaining goals, deliverables and approach.

### Proposal

Collate information from
https://docs.google.com/document/d/1yd4758eJ5u8lx97JC-tEAVkYksyviNDobefWafhc9S4/edit
https://docs.google.com/document/d/1Xwbvc8ipI2m6nlK3et-TUcrksjhV9MmNqEVFtVbtkOQ/edit
https://docs.google.com/document/d/1txIGwU2NMVQYetp77XAObLQNNHBTeVbPKC0uwUmHBGk/edit
https://docs.google.com/document/d/1F0s_G_D5g_JJncTkDReVfkxevATN2fZMPuZ5xYQ0_ds/edit

Into a single document outlining the QuickSight MVP scope and explaining the proposed approach

Update 
https://excalidraw.com/#room=df654329ca65a37051fa,TiXTabZ2QU3wsEGycccUnw

_and locate and update others_

to reflect the new QuickSight identity approach and architecture

### Additional Information

Our docs are scattered across canvasses, google docs and Excalidraw diagrams. At the end of this story we should have one or two excalidraw diagrams and one document linked in the MI/BI epic that we can all refer to when trying to understand what we're building.

### Definition of Done

- [ ] Single Source of QuickSight truth created and distributed
- [ ] User docs have been updated
- [ ] Another team member has reviewed
