### ISSUE TITLE
📝 Identify and document datasets to be used in in Quicksight MVP

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#4655]
### User Story

As a engineer
I need to know which datasets will be used in the initial Quicksight offering in AP Compute
So that I am able to share them via Lake Formation ahead of time

### Value / Purpose

There are over 1000 databases in the data-production account. By limiting the initial datasets available for use in Quicksight, we will be able to deliver our MVP earlier.

### Hypothesis

If we... limit the datasets to be shared
Then... we can release and iterate on our MVP quicker

### Proposal

Identify datasets to be used in the initial Quicksight offering in AP compute. Once we have this list, we will be in a place to do the required work to share them from the data-production account to AP compute account. We may need to liaise with data engineers and AP users to identify these datasets.

One potential approach is to share out ones currently being used in QuickSight

### Definition of Done

- [ ] Identify datasets to be used in the MVP
- [ ] List of datasets signed off
- [ ] Raise the follow-on ticket to register and share these datasets into AP Compute
