### ISSUE TITLE
📖 Embed Quicksight within the AP UI

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#4658]
### User Story

As a AP user
I want to use Quicksight embedded within the AP UI
So that I have the best user experience possible

### Value / Purpose

- Reduces the need for using the AWS console
- Users can be logged in to data-production account and use embedded quicksight side-by-side without login issues
- Allows us to use GOV UK/MOJ Design System components and branding

### Hypothesis

If we... embed Quicksight in the AP UI
Then... users will get a better experience when using it

### Proposal

Embed Quicksight (hosted in AP Compute) within the AP UI.
Users will be authenticated within QS with their Identity Centre user.
Once authenticated with QS, they will have access to resources as defined on their Identity Centre user.

### Additional Information

Initial spike POC was implemented in this draft PR (now very outdated) https://github.com/ministryofjustice/analytical-platform-ui/pull/98

### Definition of Done

- [x] [Initial POC work](https://github.com/ministryofjustice/analytical-platform-ui/pull/98) reviewed and reused where necessary
- [x] Quicksight is embedded in to the AP UI
- [x] Users are authenticated with their Identity Centre user
- [x] Test accessing data in another AWS account alongside the UI

**Comment by michaeljcollinsuk** [comment]
PR fulfils the definition of done https://github.com/ministryofjustice/analytical-platform-ui/pull/233

Next steps are:
- Attempt to deploy to dev and get feedback
- Implement managing DB access
