### ISSUE TITLE
🕵️ Investigate how existing Lake Formation is used in Data Production

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#4737]
### User Story

As an Analytical Platform engineering
I need to know how the existing Lake Formation configuration works in our Data Production
So that we don't break existing functionality when making changes for Identity Centre integration

### Value / Purpose

`IAMAllowedPrincipals` was revoked from Lake Formation causing https://github.com/ministryofjustice/data-platform-support/issues/753

### Useful Contacts

@julialawrence

### User Types

Analytical Platform engineering

### Hypothesis

If we investigate the current use of APDP's Lake Formation
Then we can understand what can and can't be done for its future state

### Proposal

I'm not quite sure on this as we were unaware it was being used, and its not entirely clear how CTAS in Athena uses Lake Formation

### Additional Information

https://docs.aws.amazon.com/athena/latest/ug/lf-athena-limitations.html#lf-athena-limitations-ctas-queries

### Definition of Done

- [ ] Investigate current Lake Formation in APDP
- [ ] Document any configuration
- [ ] Another team member has reviewed
- [ ] Tests are green
