### ISSUE TITLE
💧 Work through data-engineering-database-access repo for projects to Lake Formation Tags

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#4749]
### User Story

As a Analytical Platform team
I want to know how we currently manage database access
So that I can understand how these relate to maintaining access permissions for our users to [query tables](https://user-guidance.analytical-platform.service.justice.gov.uk/data/curated-databases/amazon-athena/#create-a-table) with Lake Formation

### Value / Purpose

[Database-access](https://github.com/moj-analytical-services/data-engineering-database-access) is the current method of granting access to databases with Athena. With the move to Lake Formation and the ability to use Tags we can improve how access is granted and speed up onboarding users to access the data they need without the need for pull requests

 
### Useful Contacts

James, Julia, Michael, RichB, Data Engineering (Gwion, Soumaya)

### Hypothesis

If we understand how we currently permission tables for 294 [Projects](https://github.com/moj-analytical-services/data-engineering-database-access/tree/main/project_access)
Then we can better spend our time developing AP-UI features that our users need

## "Dummy Migrate" a set of existing `Projects` over to use LF-Tags, this should be the target databases's we have for QuickSight MVP #4655 
- How projects are currently organised see [repo](https://github.com/moj-analytical-services/data-engineering-database-access?tab=readme-ov-file#access-to-curated-databases)
- Identify key attributes used for access control (e.g. [domain](https://github.com/moj-analytical-services/create-a-derived-table/tree/main/mojap_derived_tables/models), department, data sensitivity... or project)
### Map projects to tags
- For each project, determine which tags could apply
- Create a mapping document or spreadsheet there is an example [here](https://aws.github.io/aws-lakeformation-best-practices/lf-tags/example-usecase/)
### Review current permissions
- Analyse existing access controls
- Note which project attributes determine access levels
### Define tag-based policies
- Create Lake Formation policies using the new tags
- Ensure these policies mirror existing access controls
### Validation and testing
- Compare tag-based access to current permissions
- Test to ensure equivalent access levels

### PreReq'ish

- [ ] Projects have already been selected as part of https://github.com/ministryofjustice/analytical-platform/issues/4655

### Definition of Done

- [ ] Projects have examined and permissions reviewed
- [ ] Document the migration and create permissions mapping document
- [ ] Give team overview and create any additional issues required

**Comment by YvanMOJdigital** [comment]
@bagg3rs need more info

**Comment by YvanMOJdigital** [comment]
Work with catalog team tags stuff

**Comment by darren1988** [comment]
Park - pick up with LF work
