### ISSUE TITLE
Airflow Migration: Build out Infrastructure needed to schedule DAGs and convert to IRSA

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#480]
## User Story

We would like to implement Airflow-related infrastructure that is meant to be hosted in the Analytical Platform accounts in terraform in our Data Platform monorepo.
The whole infrastructure for Airflow is currently managed in Pulumi and the authentication of workloads to the AWS environment is accomplished with kube2iam. 

We need to refactor it into terraform as well as convert from the outdated K2IAM plug-in to the AWS-endorsed IRSA approach.

## User Type(s)

Ops Engineers, Airflow Engineers

## Value

* Alignment to tooling standards
* Refactor code 
* Improve security and manageability of the infra

## Definition of done

- [ ] DAG definitions converted to use IRSA
- [ ] Infra developed in data-platform in terraform
- [ ] Service accounts provisioned
- [ ] IRSA tested
- [ ] tests are green
- [ ] Follow-on stories raised

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jhpyke** [comment]
@jhpyke to decompose epic into tickets
