### ISSUE TITLE
🔐 Amend IAM Roles to include lakeformation:GetDataAccess permission

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4837]
### User Story

AP users need to be able to access their data based on their IAM permissions even when specific datasources are managed in LakeFormation. This needs to be a prerequisite to enrolled existing datasources into LakeFormation and sharing them for use in QuickSight, so that QS MVP does not block other platform business.

### Value / Purpose

LakeFormation allows a simpler and more granular control of data and is a preferred way of managing permissions to Glue resources than IAM.

### Useful Contacts

Julia Lawrence Michael Collins James Sott

### Hypothesis

If we add `lakeformation:getdataaccess` permission to current IAM roles, we will not cause interruption in service once LakeFormation is live.

### Proposal

1. Update all alpha roles to include the `lakeformation:getdataaccess` permissions using terraform datacall.
2. Update all app roles in a similar way
3. Review AP service IAM roles that deploy or interact with Glue resources to include this permission. For roles managed in code, this needs to be applied via code.
4. Communicate with AP users on what we're doing and why as well as provide troubleshooting instructions to fix errors that might arise.

### Additional Information

Updating alpha and app roles is fairly straight-forward but the risk is around missing a role or updating it manually when it is in code. It's key that we communicate this out broadly so that users whose roles were missed will be able to get themselves fixed quickly. 

### Definition of Done

- [ ] Comms drafted and sent out
- [ ] Alpha roles updated
- [ ] App roles updated
- [ ] Other roles updated
- [ ] Support guidance created

**Comment by julialawrence** [comment]
This isn't needed until we start transitioning to full LakeFormation. Things should work as is in hybrid mode.

**Comment by julialawrence** [comment]
This isn't needed until we start transitioning to full LakeFormation. Things should work as is in hybrid mode.
