### ISSUE TITLE
🪪 Complete Identity Center Integration With EntraID to Reach Transitional State

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4838]
### User Story

In order to deliver the QuickSight MVP, we need to finish implementing the transitional state of AWS Identity Center and EntraID integration, meaning allowing users to authenticate with either their Github or EntraID information.

### Value / Purpose

The user journey for QuickSight MVP begins with authentication via EntraID which means that the users we're inviting to the MVP need to be added to the Identity Center.
QuickSight MVP is the first stage of aligning entire AP and the AWS with our chosen identity strategy: EntraID

### Useful Contacts

@julialawrence @bag33rs

### Proposal

1. Create a python lambda that operates similarly to https://github.com/ministryofjustice/moj-terraform-scim-github to reconcile membership between EntraID groups prefixed with `aws_` and Identity Center
2. Update https://github.com/ministryofjustice/moj-terraform-scim-github to ignore EntraID users and groups when reconciling github to IC, to stop Entra users being deleted during the reconciliation.

### Definition of Done

- [ ] EntraID SCIM Lambda implemented and deployed
- [ ] Github SCIM Lambda updated and deployed
- [ ] User documentation is updated on the AP side
- [ ] Another team member has reviewed
