### ISSUE TITLE
🔒 Refactor AP Service Role Policy

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4913]
### User Story

Cut down the number of permissions in the analytical platform ui service role so it adheres to the principle of least-privilege. 

### Value / Purpose

The analytical platform UI service role is currently defined with a number of `service:*` permissions in its policy. This allows us to speed development of a critical piece of work but is not sound security-wise. Before it goes before users, we want to create a usable but secure role. 

### Useful Contacts

Michael Collins, Julia Lawrence

### User Types

AP Ops

### Proposal

Refactor this policy to only allow enough actions to perform APUI functions and remove blanket service permisions:
https://github.com/ministryofjustice/modernisation-platform-environments/blob/98f36ad5f4a2e501a7df60477d4f2a26cebd696f/terraform/environments/analytical-platform-compute/iam-policies.tf#L208

### Definition of Done

- [ ] Role policy refactored
- [ ] Policy tested
- [ ] Policy deployed
- [ ] Another team member has reviewed
- [ ] Tests are green
