### ISSUE TITLE
📖 Adjust language in the AP UI

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5459]
### User Story

As a AP UI user
I expect the language used in the UI to be clear
So that I understand what actions I am taking

### Value / Purpose

Some users reported confusion to the language during the UR sessions

### Hypothesis

If we... make the language in the UI clear
Then... users will have a better user experience

### Proposal

Improve the language used in the AP UI to make it more clear to users what there actions represent. For example, when granting access - some users reported confusion to granting "Select" permissions. Others had confusion with the concept of "Grantable permissions".

One suggestion to consider is to replace this with "Read" permissions and "Admin" permissions.

### Definition of Done

- [ ] Identify all problem areas identified in the UR sessions
- [ ] Draft possible improvements to the language
- [ ] Review options and agree language changes with the team (suggest consulting Richard Trist)
- [ ] Implement changes in the AP UI codebase
- [ ] Deploy and test changes
