### ISSUE TITLE
📖 Default to displaying "My access" on the AP UI database access page

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5460]
### User Story

As a AP UI user
I want to see what databases I have access to by default
So that I can differentiate between the list of all access

### Value / Purpose

Following feedback in UR sessions

### Hypothesis

If we... default the database access view to display databases the user has access to
Then... users will find this easier to understand that defaulting to a list of all databases

### Proposal

Update the AP UI database access view to display "My access" by default, rather than all databases

### Definition of Done

- [ ] Update database access view to display "My access" by default on page load
- [ ] Update filter logic used on the view so that hitting the url without a querystring e.g. https://analytical-platform.service.justice.gov.uk/database-access/ will default to access the users have
- [ ] Add/update unit tests to confirm user access is the default
- [ ] Changes deployed and tested in the development environmnet
