### ISSUE TITLE
📖 Search for users to grant access to tables in the AP UI

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5464]
### User Story

As a user with grantable access 
I want to search for users that I want to grant access to a table
So that I dont have to go through all users in a select box

### Value / Purpose

Will make it easier for users to find the correct user to grant access to

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

When granting access to a table, use the [MOJ search component](https://design-patterns.service.justice.gov.uk/components/search/) for the user field. This will replace the existing select component.

### Additional Information

An existing implementation is in place within Control Panel when granting access to an S3 bucket, so some of the code may be able to be reused. However as this is likely to be an old implementation, we should update as necessary. 

Example here: https://controlpanel.services.dev.analytical-platform.service.justice.gov.uk/datasources/167/access/

### Definition of Done

- [ ] Implement search component in the access form
- [ ] Tests to ensure the user is selected correctly on submission
- [ ] Deployed to dev and tested
