### ISSUE TITLE
📖 Add basic guidance on using the AP UI

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5465]
### User Story

As an AP UI user
I need guidance on using the AP UI
So that I can use it confidently and efficiently

### Value / Purpose

Providing some basic guidance on the standard flow a user may follow within the AP UI (e.g. a "first timers guide")  should help users and reduce the number of support requests we get.

### Hypothesis

If we... provide guidance on using the AP UI
Then... users will have a better user experience

### Proposal

Write some basic guidance for a "first time using AP UI" user flow within AP UI, covering the following steps:
- Logging in to the AP UI
- Checking which tables the user has access to
- Granting access to another user
- Accessing Quicksight
- Using Quicksight to create a dataset via Athena with a table the user has access to

We can then link to this guidance from the AP UI or include the guidance in the AP UI directly.

### Additional Information

Related to #5461. We should try not to duplicate guidance that is available from Quicksight.

### Definition of Done

- [ ] Draft guidance
- [ ] Team reviews the guidance and gives feedback
- [ ] Decide where guidance should live (e.g. within the UI, existing User Guidance repo etc)
- [ ] Finalised guidance written up
- [ ] Links to guidance added to the AP UI
