### ISSUE TITLE
📖 Additional filter options when viewing databases and tables in the AP UI

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5466]
### User Story

As a AP UI user
I want to filter the list of databases and tables that appear
So that I can find what I am looking for

### Value / Purpose

Additional filter options will make it easier for users to find what they are looking for

### Hypothesis

N/A

### Proposal

Consider adding additonal filter options such as:
- Databases/tables that the user does not have access to
- Databases/tables that the user has non-grantable access to
- Databases/tables that the user has grantable access to

Additionally, one user suggestion was that list of tables/databases has an additional column that shows if the user has access to it. This should be investigated, however there may be technical limitations that make this difficult, due to the list of all databases/tables being returned via boto3.

### Definition of Done

- [ ] Add additional filters listed in the proposal
- [ ] Investigate adding additional column to show access and decide if technically feasible
- [ ] Unit tests to validate filter options work as intended
- [ ] Deployed to dev environment and tested
