### ISSUE TITLE
📖 Implement Replication for `mojap-derived-tables` bucket into APC Ireland

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#5599]
0### User Story

In order to make CaDeT data available for visualisation, I would like to replicate the data held in the main output bucket into Analytical Platform Compute -- Ireland region.

### Value / Purpose

This will make the data available without compromising ongoing analytical workloads in the main account while making the latest data still available for visualisation in QS.

### Useful Contacts

Julia Lawrence, Richard Baguley

### Hypothesis

If we are able to replicate the data, we can make about 40% of our estate available for visualisation, without compromising ongoing production worklods

### Proposal

1. Migrate bucket and bucket policy from https://github.com/ministryofjustice/create-a-derived-table-infrastructure/blob/e58b7c512add0f25fc95c390089947294714e107/create_a_derived_table_infra/__main__.py#L44  into https://github.com/ministryofjustice/analytical-platform/tree/0de3665aabc10704bfa456c65faee161e8a752dd/terraform/aws/analytical-platform-data-production/data-engineering-pipelines
2. Import the bucket
3. Create a bucket [in APC Production](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/analytical-platform-compute/s3-buckets.tf) in Ireland region
4. Add and test replication configuration from CaDeT bucket into the new APC-prod bucket
5. [Use batch replication](https://aws.amazon.com/blogs/aws/new-replicate-existing-objects-with-amazon-s3-batch-replication/) to replicate existing contents to the new bucket. (requires replication to be set up between the buckets - see [existing replication setup in apc-ingestion-egress](https://github.com/ministryofjustice/analytical-platform/blob/main/terraform/aws/analytical-platform-data-production/ingestion-egress/s3.tf#L100))

### Additional Information

https://docs.google.com/document/d/1h6lft2IWB2eImFf6_Vd6DOFkLU-FNZIC0yJncmCimOc/edit

### Definition of Done

- [x] Bucket/policy code migrated
- [x] Bucket/policy imported
- [x] Bucket/policy removed from CaDeT state and code updated with new information where the bucket is managed
- [x] A story to migrate the rest of CaDeT infra raised - #5732
- [x] Replication configuration defined/implemented/tested
- [x] Existing objects replicated
