### ISSUE TITLE
Enable users to visualise CaDeT datasets in QuickSight

### ISSUE THREAD

**Issue by simon-pope** [ministryofjustice/analytical-platform#5773]
### Brief summary of what this Epic is

This epic covers the work required to speed up making CaDeT data available for visualisation in QuickSight. This will use LakeFormation.  This approach should make ~40% of AP data available for visualisation within QuickSight.  

CaDeT data has been selected as its output all lives in one bucket and it is structured in such a way that a Glue Crawler should be able to reconstruct the metadata from bucket contents, removing the need for copying/moving the metadata too.

**Acceptance Criteria**
This epic will be complete when:

1. User able to access QuickSight from within Control Panel
2. User is able to create datasources from CaDeT data
3. Users’ CaDeT permissions are replicated into QuickSight without additional work for user or AP
4. User with permissions on CaDeT data can visualise it using QS

Source document: [QS next steps (author:Julia Lawrence)](https://docs.google.com/document/d/1h6lft2IWB2eImFf6_Vd6DOFkLU-FNZIC0yJncmCimOc/edit?tab=t.0)

### List of issues in this epic

- [ ] Set up user permissions - https://github.com/ministryofjustice/analytical-platform/issues/5600
- [ ] Replicate CaDeT bucket - https://github.com/ministryofjustice/analytical-platform/issues/5599
- [ ] Users - https://github.com/ministryofjustice/analytical-platform/issues/5600
- [ ] Metadata - #5859 and #6133 
- [ ] Embed QS in to Control Panel - https://github.com/ministryofjustice/analytical-platform/issues/5532
- [ ] QuickSight Guidance and Documentation - https://github.com/ministryofjustice/analytical-platform/issues/5783

### Other information

- Roadmap deliverable - New Feature
- Target delivery date January '24
