### ISSUE TITLE
⛰ Upgrade Airflow

### ISSUE THREAD

**Issue by simon-pope** [ministryofjustice/analytical-platform#5847]
### Brief summary of what this Epic is

Currently we provide Airflow 2.4.3, currently available version is 2.10.x which we need to move to.  We need to create a new environment in to APC environments which will have this version.  

This epic will cover the upgrade and support.  A follow up epic may cover improvements on this.

### List of issues in this epic

- [ ] Agree and document architecture to support the upgrade using SSO to provide CP with identify within Airflow. Include logging, monitoring and observability (user facing and platform)
- [ ] Build out of Dev environment
- [ ] Identify set of DAGS to take through upgrade process (Decision as to whether this is AP team + user or not)
- [ ] Extract steps required and document them, recording breaking changes and changes required by users to permissions etc
- [ ] Identify larger group of users to test instructions
- [ ] Build our test environment to support more users
- [ ] Allow more users to migrate across
- [ ] Support full migration of DAGs to 2.10.x
- [ ] Retire 2.4.3

DOD
- [ ] All Airflow environments in APC running 2.10.x
- [ ] All DAGs migrated to 2.4.3
- [ ] Control Panel updated to support new environment
- [ ] 2.4.3 is fully retired from all environments

### Other information

Nice to have? Support for new features provided by 2.10.x

**Comment by jhpyke** [comment]
Supeceded by #6543
