### ISSUE TITLE
✨ Build RStudio image

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#5861]
### User Story

As an Analytical Platform engineer
I want to release one single image of RStudio that covers functionality 🤷 `<to be defined>`
So that users have one RStudio release to use and we have one RStudio release to support

### Value / Purpose

We want to offer a minimal JupyterLab image, based on the Analytical Platform Cloud Development Environment Base Image, for users of the Analytical Platform.

### Useful Contacts

@jacobwoffenden @Gary-H9

### User Types

Analytical Platform Users

### Proposal

Build a RStudio offering from scratch like we do for Visual Studio Code, allowing us to understand and control the entire offering.

Subject to user research this image may need other functionality.

### Additional Information

I think this task can be broken down into two parts: 
a) Install R - as per [here](https://cran.rstudio.com/). - already done in the APCBDE image [here](https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-base/blob/237e8c4cc92d79aa5a9780c7ccb223a9e3b7ed16/Dockerfile#L211). ✅ 
b) Install RStudio - as per [here](https://posit.co/download/rstudio-desktop/).
Information from the [old repository](https://github.com/ministryofjustice/analytics-platform-rstudio) should also be considered as part of this work as (presumably) challenges which were met there were overcome, we should try and avoid duplicating previous efforts.

RStudio doesn't seem to do releases as we'd [expect](https://github.com/rstudio/rstudio/releases) and rather releases [tarballs](https://posit.co/download/rstudio-server/) based on [tags](https://github.com/rstudio/rstudio/tags) (I think?).

### Definition of Done

- [ ] Create a restricted release within prod environment for us to test
- [ ] Private beta?
- [ ] Make the release generally available
- [ ] Adopt deprecation plan which is in place for JupyterLab
- [ ] Send comms to users about the upgrade

**Comment by jacobwoffenden** [comment]
Moving to blocked while we figure out a rollout plan

**Comment by jacobwoffenden** [comment]
Moving to backlog, will be picked in 2025
