### ISSUE TITLE
Convert Create a Derived Table Infra repo to Terraform

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#793]
Start the conversion of the create-a-derived-table-infrastructure repository from Pulumi to Terraform.

https://github.com/ministryofjustice/create-a-derived-table-infrastructure

Converting tests is out of scope.

Infra covered is:

- [ ] `mojap-derived-tables` bucket and associated policy
- [ ] `dbt-query-dump` bucket and policy
- [ ] `cleanup-non-prod-databases` lambda function and associated role/role policy
- [ ] `eventbridge` rules and triggers relating to the above lambda function

**Comment by jhpyke** [comment]
@jhpyke to update with detail of infra to port

**Comment by julialawrence** [comment]
Jacob to refine with list of resources.
