### ISSUE TITLE
👷 Address Remaining Terraform static analysis alerts

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#886]
On a pull request Terraform will perform static analysis using Checkov and tfsec, however components other than `aws-analytical-platform-development-open-metadata` haven't been processed

As of 19/07/2023, the following components are;

- [x] aws-analytical-platform-baseline 
- [ ] aws-analytical-platform-data-engineering-production-10ds
- [x] aws-analytical-platform-oidc
- [ ] github
- [x] pagerduty
- [ ] aws-analytical-platform-data-production-control-panel-message-broker
- [ ] aws-analytical-platform-development-control-panel-message-broker
- [x] aws-analytical-platform-development-sagemaker

# Proposal
Run static code analysis (within the dev container) on each component in turn, then remediate or skip issues flagged

# Definition of Done:

- [ ] All warnings addressed (including remediated or skipped)

**Comment by BrianEllwood** [comment]
List updated

**Comment by BrianEllwood** [comment]
I have put together the following [spread sheet](https://docs.google.com/spreadsheets/d/1QkAAbCNeKIW1EonTWPm9ljTy1WII_ONlw2YqFRYtI-U/edit?usp=sharing) with my findings from the checkov run for aws-analytical-platform-development-cluster.  could i please have a review of my findings/approach and i will work on the trivy check in the interim. Thanks @jacobwoffenden @julialawrence

**Comment by BrianEllwood** [comment]
trivy -  All issues detected by `trivy config . -s CRITICAL`  in the data-platform/terraform/aws/analytical-platform-development/cluster directory are from files  below the terraform/modules do we want to check these modules  ?

**Comment by BrianEllwood** [comment]
@jacobwoffenden can you confirm if we want to check the .terraform/modules please ?

**Comment by BrianEllwood** [comment]
As trivy does not provide a csv format i have been attempting to convert the json output to csv file, the method i attempted had a logic issue i could not resolve. another method was suggested using pandas but i have hit errors straight away and rather than waste any more time  on this i will move on to addressing the issues raised by trivy.

**Comment by BrianEllwood** [comment]
[text output for trivy scan](https://docs.google.com/document/d/1QDAQiONnUemo0s2b3WgS6_oPaXncSYfoE6R4sjGO8FE/edit)

**Comment by BrianEllwood** [comment]
Following review of checkov output, actions agreed

1 implement skips for CKV_TF_1 and create PR's

2 code, plan and create PRs for recommended implements - do not run into code 

3 once action 2 complete re-review skips

**Comment by BrianEllwood** [comment]
awaiting PR review

**Comment by BrianEllwood** [comment]
Action 1 implement skips for CKV_TF_1 and create PR's 


completed in [this PR](https://github.com/ministryofjustice/data-platform/pull/2664l)

**Comment by BrianEllwood** [comment]
currently working through the checkov issues in analytical-platform-development/cluster

**Comment by BrianEllwood** [comment]
I have created [pr](https://github.com/ministryofjustice/data-platform/pull/2836)

Checkov scan results for analytical-platform-development-cluster

Passed checks: 267, Failed checks: 0, Skipped checks: 30

**Comment by jacobwoffenden** [comment]
Moving to blocked while @BrianEllwood is on AL

**Comment by Emterry** [comment]
10ds nearly completed - outstanding pull request

**Comment by AntFMoJ** [comment]
I have picked up the aws-analytical-platform-development-control-panel-message-broker next.

**Comment by Ed-Bajo** [comment]
None urgent work.
